CREATE OR REPLACE FUNCTION USER_CHESSRUSH.F_LVL_CHECK_HERO_SLOT_CHANCE (
   P_HERO_TIER_ID    NUMBER
)
   RETURN NUMBER
IS
   V_HERO_ID   NUMBER;
BEGIN
   SELECT   HERO_ID
     INTO   V_HERO_ID
     FROM   (  SELECT   HERO_ID
                 FROM   CR_HERO
                WHERE   HERO_TIER_ID = P_HERO_TIER_ID
                        AND HERO_STATUS_CODE = 'A'
             ORDER BY   DBMS_RANDOM.VALUE)
    WHERE   ROWNUM = 1;

   RETURN V_HERO_ID;
END;
/


