CREATE OR REPLACE FUNCTION USER_CHESSRUSH.F_PREVIEW_SYNERGY_CLASS (P_CLASS_ID        NUMBER,
                                                   P_CLASS_AMOUNT    NUMBER)
   RETURN NUMBER
IS
   V_SYNERGY_ID   NUMBER;
BEGIN
   BEGIN
      SELECT   MAX (SYNERGY_ID)
        INTO   V_SYNERGY_ID
        FROM   (SELECT   SYNERGY_ID, SYNERGY_NAME, CLASS_AMOUNT
                  FROM   CR_SYNERGY
                 WHERE   CLASS_ID = P_CLASS_ID AND CLASS_AMOUNT <= P_CLASS_AMOUNT);
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         V_SYNERGY_ID := NULL;
   END;

   RETURN V_SYNERGY_ID;
END;
/


