CREATE OR REPLACE FUNCTION USER_CHESSRUSH.F_PREVIEW_COMBINE_HERO (
   P_SESSION_ID      NUMBER,
   P_HERO_ID         NUMBER,
   P_MANA_CRYSTAL    NUMBER,
   P_STAR_GRADE      NUMBER
)
   RETURN NUMBER
IS
   V_HERO_ID                 NUMBER;
   V_STAR_GRADE              NUMBER;
   V_COUNT_HERO              NUMBER;
   V_COUNT_CLASS             NUMBER;
   V_CLASS_AMOUNT_PREVIEW    NUMBER;
   V_CLASS_AMOUNT            NUMBER;
   V_BONUS_MANA_CRYSTAL      NUMBER;
   V_MANA_CRYSTAL_REQUIRED   NUMBER;
BEGIN
   --SPECIAL FOR DRUID
   SELECT   COUNT ( * )
     INTO   V_COUNT_CLASS
     FROM   CR_HERO
    WHERE   HERO_ID = P_HERO_ID AND CLASS_ID = 8;

   --IF HERO CLASS IS NOT DRUID THEN NO BONUS MANA CRYSTAL FOR UPGRADE
   IF V_COUNT_CLASS = 0
   THEN
      V_BONUS_MANA_CRYSTAL := 0;
   ELSE
      --IF HERO CLASS IS DRUID, CHECK HOW MUCN UNIQUE DRUID IN THE BENCH AND ARENA
      SELECT   CLASS_AMOUNT
        INTO   V_CLASS_AMOUNT_PREVIEW
        FROM   V_PREVIEW_COMBINE_HERO_CLASS
       WHERE   SESSION_ID = P_SESSION_ID AND CLASS_ID = 8;

      ---CHECK IF UNIQUE HERO DRUID AMOUNT MEETS SYNERGY, TAKE THE LEAST SYNERGY
      FOR X IN (  SELECT   CLASS_AMOUNT
                    FROM   CR_SYNERGY
                   WHERE   CLASS_ID = 8
                ORDER BY   CLASS_AMOUNT ASC)
      LOOP
         IF V_CLASS_AMOUNT_PREVIEW >= X.CLASS_AMOUNT
         THEN
            V_CLASS_AMOUNT := X.CLASS_AMOUNT;
         END IF;
      END LOOP;

      --COUNT HOW MUCH OF SAME HERO WITH SAME STAR GRADE IN THE BENCH AND ARENA
      SELECT   COUNT ( * )
        INTO   V_COUNT_HERO
        FROM   (SELECT   SESSION_ID, HERO_ID, STAR_GRADE FROM CR_PREVIEW_ARENA
                UNION ALL
                SELECT   SESSION_ID, HERO_ID, STAR_GRADE FROM CR_PREVIEW_BENCH)
       WHERE       SESSION_ID = P_SESSION_ID
               AND HERO_ID = P_HERO_ID
               AND STAR_GRADE = P_STAR_GRADE;

      IF V_COUNT_HERO < 2
      THEN
         V_BONUS_MANA_CRYSTAL := 0;
      ELSE
         --CALCULATE THE BONUS MANA CRYSTAL FOR DRUID
         SELECT   POWER (V_CLASS_AMOUNT, 3-1) INTO V_BONUS_MANA_CRYSTAL FROM DUAL;
      END IF;
   END IF;

   --CALCULATE MANA CRYSTAL THAT REQUIRED FOR UPGRADE
   V_MANA_CRYSTAL_REQUIRED := P_MANA_CRYSTAL + V_BONUS_MANA_CRYSTAL;

     --CHECK IF THE HERO CAN BE UPGRADE WITH SUCH AMOUNT OF MANA CRYSTAL
     SELECT   HERO_ID, MAX (STAR_GRADE)
       INTO   V_HERO_ID, V_STAR_GRADE
       FROM   V_MST_HERO_PROFILE
      WHERE   HERO_ID = P_HERO_ID AND MANA_CRYSTAL <= V_MANA_CRYSTAL_REQUIRED
   GROUP BY   HERO_ID;

   --IF HERO CAN NOT BE UPGRADED YET THEN GIVE NULL VALUE
   IF V_STAR_GRADE = P_STAR_GRADE
   THEN
      V_STAR_GRADE := NULL;
   END IF;

   RETURN V_STAR_GRADE;
END;
/


