CREATE OR REPLACE FUNCTION USER_CHESSRUSH.F_PREVIEW_SYNERGY_RACE (P_RACE_ID        NUMBER,
                                                   P_RACE_AMOUNT    NUMBER)
   RETURN NUMBER
IS
   V_SYNERGY_ID   NUMBER;
BEGIN
   BEGIN
      SELECT   MAX (SYNERGY_ID)
        INTO   V_SYNERGY_ID
        FROM   (SELECT   SYNERGY_ID, SYNERGY_NAME, RACE_AMOUNT
                  FROM   CR_SYNERGY
                 WHERE   RACE_ID = P_RACE_ID AND RACE_AMOUNT <= P_RACE_AMOUNT);
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         V_SYNERGY_ID := NULL;
   END;

   RETURN V_SYNERGY_ID;
END;
/


