/* Formatted on 21/02/2023 21:51:45 (QP5 v5.114.809.3010) */
CREATE OR REPLACE FORCE VIEW USER_CHESSRUSH.V_APP_INVALID_USER
(
   ROLE_ID,
   USER_NAME
)
AS
     SELECT   ROLE_ID, USER_NAME
       FROM   APP_USER
      WHERE   ROLE_ID NOT IN (  SELECT   ROLE_ID FROM APP_ROLE)
   ORDER BY   ROLE_ID;


