SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_ROLE
--
Insert into USER_CHESSRUSH.APP_ROLE
   (ROLE_ID, ROLE_NAME, ROLE_STATUS, DATE_CREATE, USER_CREATE)
 Values
   (1, 'ADMIN', 'A', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
