SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_API_ACCESS_TYPE
--
Insert into USER_CHESSRUSH.APP_API_ACCESS_TYPE
   (ACCESS_TYPE_ID, ACCESS_NAME, VALID_UNTIL, PRICE, IS_ACTIVE, DATE_CREATE, USER_CREATE)
 Values
   (1, 'ALL ACCESS', TO_DATE('12/31/2050 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 100000, 'Y', TO_DATE('11/09/2019 09:45:20', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
