SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_API_STATUS
--
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (1, '200', 'OK', TO_DATE('11/09/2019 09:54:27', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (2, '201', 'CREATED', TO_DATE('11/09/2019 09:54:34', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (3, '202', 'ACCEPTED', TO_DATE('11/09/2019 09:54:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (4, '204', 'NO CONTENT', TO_DATE('11/09/2019 09:55:15', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (5, '301', 'MOVED PERMANENTLY', TO_DATE('11/09/2019 09:55:45', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (6, '302', 'FOUND', TO_DATE('11/09/2019 09:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (7, '303', 'SEE OTHER', TO_DATE('11/09/2019 09:56:21', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (8, '304', 'NOT MODIFIED', TO_DATE('11/09/2019 09:56:35', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (9, '307', 'TEMPORARY REDIRECT', TO_DATE('11/09/2019 09:56:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (10, '400', 'BAD REQUEST', TO_DATE('11/09/2019 09:57:07', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (11, '401', 'UNAUTHORIZED', TO_DATE('11/09/2019 09:57:21', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (12, '403', 'FORBIDDEN', TO_DATE('11/09/2019 09:57:33', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (13, '404', 'NOT FOUND', TO_DATE('11/09/2019 09:57:45', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (14, '405', 'METHOD NOT ALLOWED', TO_DATE('11/09/2019 09:58:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (15, '406', 'NOT ACCEPTABLE', TO_DATE('11/09/2019 09:58:32', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (16, '412', 'PRECONDITION FAILED', TO_DATE('11/09/2019 09:58:59', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (17, '415', 'UNSUPPORTED MEDIA TYPE', TO_DATE('11/09/2019 09:59:18', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (18, '500', 'INTERNAL SERVER ERROR', TO_DATE('11/09/2019 09:59:34', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (19, '501', 'NOT IMPLEMENTED', TO_DATE('11/09/2019 09:59:53', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_STATUS
   (API_STATUS_ID, API_STATUS_CODE, API_STATUS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (20, '999', 'DATA NOT FOUND', TO_DATE('11/09/2019 11:20:17', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
