SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_ROLE_MENU
--
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, 1, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (2, 1, 2, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (3, 1, 3, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (4, 1, 4, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (5, 1, 5, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (6, 1, 6, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (7, 1, 7, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (8, 1, 8, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (9, 1, 9, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (10, 1, 10, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (11, 1, 11, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (12, 1, 12, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (13, 1, 13, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (14, 1, 14, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (15, 1, 15, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (16, 1, 16, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (17, 1, 17, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (18, 1, 18, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (19, 1, 19, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (20, 1, 20, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (21, 1, 21, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (22, 1, 22, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (23, 1, 23, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
