SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_USER_ACTIVATION_LOG
--
Insert into USER_CHESSRUSH.APP_USER_ACTIVATION_LOG
   (ACTIVATION_ID, USER_ID, ACTIVATION_SENT_DATE, ACTIVATION_SENT_STATUS, ACTIVATION_SENT_DESC, ACTIVATION_REC_DATE, ACTIVATION_REC_STATUS, ACTIVATION_REC_DESC, ACTIVATION_STATUS, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, TO_DATE('11/09/2019 09:41:37', 'MM/DD/YYYY HH24:MI:SS'), '200', 'SUCCESS', TO_DATE('11/09/2019 09:42:02', 'MM/DD/YYYY HH24:MI:SS'), '200', 'SUCCESS', 'A', TO_DATE('11/09/2019 09:37:25', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
