SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_STATISTIC_UNIQUE_HIT
--
Insert into USER_CHESSRUSH.APP_STATISTIC_UNIQUE_HIT
   (UNIQUE_HIT_ID, UNIQUE_DATE_HIT, UNIQUE_IP_ADDRESS, COUNTRY)
 Values
   (1, TO_DATE('11/09/2019 09:51:34', 'MM/DD/YYYY HH24:MI:SS'), '127.0.0.1', 'INDONESIA');
COMMIT;
