SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_API_ACCESS_DETAIL
--
Insert into USER_CHESSRUSH.APP_API_ACCESS_DETAIL
   (ACCESS_DETAIL_ID, ACCESS_ID, IP_ADDRESS, IP_TYPE, IS_ACTIVE, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, '127.0.0.1', 'IPV4', 'Y', TO_DATE('11/09/2019 09:47:28', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.APP_API_ACCESS_DETAIL
   (ACCESS_DETAIL_ID, ACCESS_ID, IP_ADDRESS, IP_TYPE, IS_ACTIVE, DATE_CREATE, USER_CREATE)
 Values
   (2, 1, '10.1.18.100', 'IPV4', 'Y', TO_DATE('11/09/2019 09:47:49', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
