SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.APP_MESSAGE
--
Insert into USER_CHESSRUSH.APP_MESSAGE
   (MESSAGE_ID, NAME, EMAIL, MESSAGE, IP_ADDRESS, DATE_CREATE, USER_CREATE)
 Values
   (1, 'ROMTONI', 'romtoni21@gmail.com', 'TEST', '127.0.0.1', TO_DATE('11/09/2019 09:23:42', 'MM/DD/YYYY HH24:MI:SS'), 'ANONYMOUS');
COMMIT;
