SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_SKILL
--
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, 2, 'img/skill/Taunt.png', 'TAUNT', 'SHOUTS TO ATTRACT ATTENTION OF ENEMIES WITHIN 1 GRID AND FORCES THEM TO ATTACK HIM. IGNORES ABILITY IMMUNITY AND INCREASES ARMOR BY 25/50/75 FOR 2/3/4S.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (2, 2, 1, 'img/skill/Quick_Assault.png', 'QUICK ASSAULT', 'WHEN ATTACKING THE SAME ENEMY, EACH CONSECUTIVE NORMAL ATTACK INCREASES ATTACK SPEED BY 9/ 12/ 15, UP TO 10/15/20 TIMES. HALF OF THE STACKS ARE LOST WHEN SWITCHING TO ANOTHER TARGET.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (3, 3, 1, 'img/skill/Energy_Blade.png', 'ENERGY BLADE', 'FIRES AN ENERGY BLADE AT A RANDOM ENEMY (HIGH CHANCE TO ATTACK THE NEAREST ENEMY), DEALING 600/1000/1400 MAGIC DAMAGE AND STUNNING THE TARGET FOR 0.75S. THIS ABILITY DEALS DOUBLE DAMAGE TO ENEMIES WITH A LOWER LEVEL.5 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (4, 4, 3, 'img/skill/Dark_Space.png', 'DARK SPACE', 'GRANTS THE ALLY WITH LOWEST HEALTH A SHIELD THAT ABSORBS UP TO 300/450/600 DAMAGE. THE SHIELD LASTS 1OS AND EXPLODES AFTER ABSORBING THE MAXIMUM AMOUNT OF DAMAGE, DEALING 300/450/600 MAGIC DAMAGE TO ENEMIES WITHIN 3 GRIDS.12 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (5, 5, 1, 'img/skill/Dragon_Form.png', 'DRAGON FORM', 'TRANSFORMS INTO A DRAGON, INCREASING ATTACK DAMAGE BY 200/350/500 AND ATTACK RANGE BY 3 SQUARES. THE DRAGON''S ATTACKS DEAL 30%/60%/90% SPLASH DAMAGE TO ENEMIES WITHIN 1/2/2 SQUARES OF THE TARGET.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (6, 6, 1, 'img/skill/Devouring_Plant.png', 'DEVOURING PLANT', 'SUMMONS A FLOWER SPIRIT WITH 150/210/270 ATTACK DAMAGE AND 1500/2100/2700 HP.7 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (7, 7, 1, 'img/skill/Seed_Of_Nature.png', 'SEED OF NATURE', 'CASTS A SEED OF NATURE ATA RANDOM ENEMY, DEALING 90/120/150 MAGIC DAMAGE EVERY 1.5S WHILE HEALING THE ALLIES WITHIN 3 GRIDS FOR THE SAME AMOUNT. LASTS 5S.8 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (8, 8, 1, 'img/skill/Soul_Siphon.png', 'SOUL SIPHON', 'GAINS 10 ATTACK DAMAGE FOR EVERY UNIT KILLED IN BATTLE. STACKS UP TO 6/8/10 TIMES.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (9, 9, 1, 'img/skill/Whirling_Blades.png', 'WHIRLING BLADES', 'TOSSES TWO BLADES THAT TRAVEL FORWARD AND RETURN. EACH BLADE DEALS 210/330/450 PHYSICAL DAMAGE TO ENEMIES ON ITS PATH. THOSE HIT BY THE BLADES TAKE 10%/20%30% EXTRA DAMAGE.6 SECONDS COOLDOWN', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (10, 10, 1, 'img/skill/Cleansing_Flame.png', 'CLEANSING FLAME', 'CREATES AN EXPLOSION ON THE ENEMY WITH THE HIGHEST LEVEL, DEALING 1500/2250/3000 MAGIC DAMAGE. IF THE TARGET DIES, THE REMAINING DAMAGE IS DEALT TO NEARBY ENEMIES.5 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (11, 11, 1, 'img/skill/Full_Swing.png', 'FULL SWING', 'HURLS A BOOMERANG AFTER CHARGING FOR 0.5S, DEALING 1200/1800/2400 MAGIC DAMAGE TO ENEMIES ON ITS PATH. IF INTERUPTED WHILE CHARGING, THE BOOMERANG WILL BE THROWN IMMEDIATELY.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (12, 12, 1, 'img/skill/Frozen_Storm.png', 'FROZEN STORM', 'CREATES A STORM AT THE FEET OF A RANDOM ENEMY, DEALING 250/425/600 MAGIC DAMAGE PER SECOND TO ALL ENEMIES WITHIN 4 GRIDS AND SLOWING THEM BY 40% FOR 3S.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (13, 13, 1, 'img/skill/Water_Bolt.png', 'WATER BOLT', 'FIRES JETS OF WATER AT 2 RANDOM ENEMIES, DEALING 150/225/300 MAGIC DAMAGE AND REDUCING THE TARGETS'' ARMOR BY 50/75/150 FOR 20S.3 SECONDS COOLDOWN', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (14, 14, 2, 'img/skill/Light_Of_Leadership.png', 'LIGHT OF LEADERSHIP', 'SUMMONS A MAGIC SWORD ABOVE A RANDOM ENEMY. THE SWORD FALLS AFTER 3S, DEALING 400/550/700 MAGIC DAMAGE TO ALL ENEMIES WITHIN 3 SQUARES AND STUNNING THEM FOR 1.4S.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (15, 15, 1, 'img/skill/Grim_Slash.png', 'GRIM SLASH', 'SLASHES ALL ENEMIES IN THE FRONT AND ABSORBS THEIR SOULS, DEALING 450/600/750 MAGIC DAMAGE. FOR EVERY ENEMY HIT, RESTORES 12%/16%/20% OF HEALTH LOST.8 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (16, 16, 1, 'img/skill/Smash.png', 'SMASH', 'SMASHES THE GROUND TO DEAL 400/550/700 TRUE DAMAGE TO ENEMIES WITHIN 2 GRIDS.6/5/4 SECONDS COOLDOWN', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (17, 17, 4, 'img/skill/I_Am_Gurru.png', 'I AM GURRU', 'GURRU LOVES PEACE AND REFUSES TO FIGHT. WHEN YOU HAVE 2 IDENTICAL HEROES, YOU CAN DRAG GURRU WITH SAME STAR ON EITHER OF THEM TO COMBINE THEM INTO A HIGHER LEVEL HERO.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (18, 18, 1, 'img/skill/Death_From_Above.png', 'DEATH FROM ABOVE', 'DEALS HIGH DAMAGE TO THE ENEMY WITH THE LOWEST HP. IF TARGET IS KILLED, IT REDUCES 80% OF THE COOLDOWN AND 80 MANA WILL BE RETURNED.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (19, 19, 1, 'img/skill/Charrrrrrge.png', 'CHARRRRRRGE', 'AFTER TAKING LETHAL DAMAGE, CHARGES TOWARDS THE NEAREST ENEMY AND DEALS 400/600/800 MAGIC DAMAGE TO ALL TARGETS WITHIN 1 GRID, STUNNING THEM FOR 0.5S.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (20, 20, 1, 'img/skill/Dash.png', 'DASH', 'DASHES FORWARD AND DEALS 450/750/1050 MAGIC DAMAGE TO ENEMIES ON THE PATH. TARGETS ARE ALSO STUNNED FOR 2S.8 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (21, 21, 1, 'img/skill/Glacier_Strike.png', 'GLACIER STRIKE', 'DEALS 300%/350%/400% PHYSICAL DAMAGE TO AN ENEMY WITHIN 1 GRID AND KNOCKING IT INTO THE AIR FOR IS. IGNORES ABILITY IMMUNITY.7 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (22, 22, 1, 'img/skill/Fury_Of_Deep_Sea.png', 'FURY OF DEEP SEA', 'SUMMONS SHARKS, DEALING 450/750/1050 MAGIC DAMAGE TO ENEMIES WITHIN 4/5/6 GRIDS AND STUNNING THEM FOR 2/2.5/3S.30 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (23, 23, 2, 'img/skill/Deepsea_Coil.png', 'DEEPSEA COIL', 'SPITS INK FOR 4S. ENEMIES STILL AFFECTED BY THE INK AFTER 2S HAVE A 80%/90%/100% CHANCE OF BEING STUNNED FOR 3S AND TAKE 400/550/700 MAGIC DAMAGE. STUNNED ENEMIES ALSO TAKE AN ADDITIONAL 30% PHYSICAL DAMAGE.20 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (24, 24, 1, 'img/skill/Holy_Light.png', 'HOLY LIGHT', 'UNLEASHES A SHOCKWAVE AFTER 3S, DEALING 600/900/1200 DAMAGE TO ALL ENEMIES IN ITS PATH. MAGIC DAMAGE INCREASES BY 200/300/400 FOR EVERY 1S SPENT CHARGING. SHOCKWAVE IS UNLEASHED IMMEDIATELY IF CHARGING IS INTERRUPTED.14/12/10 SECONDS', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (25, 25, 1, 'img/skill/Death_Bloom.png', 'DEATH BLOOM', 'TOSSES A LARGE AMOUNT OF MAGIC BLADES AT ENEMIES WITHIN 3 GRIDS, DEALING 525/675/825 MAGIC DAMAGE.6 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (26, 26, 1, 'img/skill/Incubate.png', 'INCUBATE', 'SUMMONS A FROGLING WHOSE ATTACKS REDUCE THE TARGET''S ATTACK SPEED BY 30%. THE FROGLING IS IMMUNE TO ENEMY ABILITIES, AND HAS 250/400/550 ATTACK DAMAGE AND 400/700/1000 HP.9/8/7 SECONDS COOLDOWN', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (27, 27, 1, 'img/skill/Shadow_Pulse.png', 'SHADOW PULSE', 'CASTS A SHADOW PULSE THAT DEALS 300/450/600 MAGIC DAMAGE TO ENEMIES WITHIN 3 GRIDS AND HEALS ALLIES (INCLUDING HERSELF) FOR 300/450/600.5 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (28, 28, 1, 'img/skill/Sonic_Blast.png', 'SONIC BLAST', 'FIRES THREE SONIC PROJECTILES THAT DEAL 300/525/750 MAGIC DAMAGE TO RANDOM ENEMIES.7 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (29, 29, 1, 'img/skill/Natures_Breath.png', 'NATURES BREATH', 'FIRES A MAGIC ORB INFUSED WITH NATURAL ENERGY. THE ORB MOVES FORWARD FOR 7 GRIDS AND DEALS 300/400/500 MAGIC DAMAGE TO ENEMIES IN ITS PATH, AS WELL AS RECOVERS ALLIES'' HEALTH BY 150/200/250.5/4/3 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (30, 30, 1, 'img/skill/Fire_Blast.png', 'FIRE BLAST', 'CREATES LOTS OF EXPLOSIONS NEARBY, EACH DEALING 300/450/600 MAGIC DAMAGE.20 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (31, 31, 1, 'img/skill/Soul_Blade.png', 'SOUL BLADE', 'EACH ATTACK DEALS 33/66/100 TRUE DAMAGE AND REDUCES TARGET''S MANA BY THE SAME AMOUNT, WHILE ALSO INCREASING OWN MAGIC RESISTANCE BY 30%/40%/50%.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (32, 32, 1, 'img/skill/Summon_Nightowl_Spirit.png', 'SUMMON NIGHTOWL SPIRIT', 'SPIRIT SUMMONS A NIGHTOWL SPIRIT WITH 350/550/850 ATTACK DAMAGE AND 3000/4000/5000 HEALTH TO FIGHT ENEMIES. ITS ATTACKS HAVE A 25% CHANCE TO STUN ITS TARGETS FOR 2S.60 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (33, 33, 1, 'img/skill/Flames_Of_War.png', 'FLAMES OF WAR', 'BUNCHES A FIREBALL AT A RANDOM ENEMY, DEALING 400/600/800 MAGIC DAMAGE AND STUNNING THE TARGET FOR 1.5/2/2.5S. IF OWN HEALTH PERCENTAGE IS HIGHER THAN THE TARGET''S HEALTH PERCENTAGE, INCREASES DAMAGE DONE BY 50%; OTHERWISE, EXTENDS THE STUN DURATION BY 1S.5 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (34, 34, 2, 'img/skill/Sirens_Song.png', 'SIRENS SONG', 'SINGS THE SONG OF THE SIREN, MAKING ENEMIES WITHIN 1 GRID ATTACK THEIR ALLIES FOR 2.5/3.5/4.5S.10/8/6 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (35, 35, 1, 'img/skill/Judgement.png', 'JUDGEMENT', 'EACH NORMAL ATTACK HAS 30% CHANCE OF TRANSFORMING INTO A LASER BEAM. THE LASER BEAM DEALS 20%/30%/40% PHYSICAL DAMAGE AND BOUNCES BETWEEN 3/4/5 ENEMIES, EACH BOUNCE DEALING 30% DAMAGE.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (36, 36, 2, 'img/skill/Meditation.png', 'MEDITATION', 'CREATES A SILENCING ZONE AT A RANDOM ENEMY LOCATION, DEALING 250/375/500 MAGICAL DAMAGE TO NEARBY ENEMIES EVERY SECOND AND SILENCING THEM FOR 3S.20 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (37, 37, 1, 'img/skill/Lava_Blast.png', 'LAVA BLAST', 'FIRES A LAVA BLAST AT A RANDOM ENEMY WITHIN 2 GRIDS EVERY 0.7S FOR 5S, DEALING 150/225/300 MAGIC DAMAGE AND STUNNING THE TARGET FOR 0.75S.12/10/8 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (38, 38, 1, 'img/skill/Creeping_Revelation.png', 'CREEPING REVELATION', 'GRANTS NORMAL ATTACKS A 15% CHANCE TO BE CRITICAL HITS, DEALING 350%/475%/600% PHYSICAL DAMAGE.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (39, 39, 3, 'img/skill/Phantom_Formation.png', 'PHANTOM FORMATION', 'SUMMONS AN ARRAY OF PHANTOM SWORDS THAT GRANTS SWORD DANCER A SHIELD THAT BLOCKS 4/6/8 ATTACKS AND 4/6/8 DAGGERS THAT INCREASE ATTACK DAMAGE BY 120/180/240 EACH, CONSUMED WITH EACH NORMAL ATTACK.6 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (40, 40, 5, 'img/skill/Blessing_Light.png', 'BLESSING LIGHT', 'CASTS A HOLY LIGHT ON THE ALLY WITH LOWEST HEALTH (INCLUDING HIMSELF) TO RESTORE 600/900/1200 HEALTH AND DEAL 600/900/1200 TRUE DAMAGE TO ENEMIES WITHIN 2 GRIDS.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (41, 41, 1, 'img/skill/Calling_Fleet.png', 'CALLING FLEET', 'CALLS FLEET TO ATTACK A RANDOM ENEMY AFTER 1.5S AND 3S, EACH ATTACK DEALING 600/900/1200 MAGIC DAMAGE TO ALL ENEMIES WITHIN 5 GRIDS.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (42, 42, 1, 'img/skill/Nightmare_Blast.png', 'NIGHTMARE BLAST', 'FIRE A NIGHTMARE BLAST AT ONE RANDOM ENEMY. THE BLAST BOUNCES BETWEEN ENEMIES WITHIN 4 GRIDS OF THE ORIGINAL TARGET AND DEALS 600/900/1200 MAGIC DAMAGE EACH TIME FOR A TOTAL OF 6/9/12 TIMES. EACH BOUNCE ALSO REDUCES THE TARGET''S ATTACK SPEED BY 65 FOR 2.5S.10/8/6 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (43, 43, 1, 'img/skill/Metamorphosis.png', 'METAMORPHOSIS', 'TRANSFORMS INTO A DEMON AND DRAINS A RANDOM ENEMY''S HEALTH BY 50%. BECOMES A RANGED HERO AND GAINS 50/100/200 ATTACK DAMAGE AND 65 ATTACK SPEED.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (44, 44, 1, 'img/skill/Curse.png', 'CURSE', 'CURSES AN ENEMY WITH HIGHEST LEVEL, DEALING 180/270/360 TRUE DAMAGE EVERY SECOND AND STOPPING THE TARGET FROM USING ABILITIES FOR 20S. IGNORES ABILITY IMMUNITY.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (45, 45, 1, 'img/skill/Time_Bomb.png', 'TIME BOMB', 'PLANTS A TIME BOMB NEARBY THAT EXPLODES AFTER 3S, DEALING 1800/2400/3000 PHYSICAL DAMAGE TO ENEMIES WITHIN 5 GRIDS.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (46, 46, 2, 'img/skill/Body_Swap.png', 'BODY SWAP', 'SWAP THE BODY OF A RANDOM ENEMY WITH A WEAK ANIMAL FOR 4/6/8S, RENDERING THE TARGET UNABLE TO ATTACK OR USE ABILITIES.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (47, 47, 1, 'img/skill/Wind_Blade.png', 'WIND BLADE', 'THE FLYING DAGGER FROM EACH ATTACK WILL BOUNCE BETWEEN ENEMIES WITHIN 4 GRIDS UP TO 3/5/7 TIMES AFTER IT HITS AN ENEMY. EACH BOUNCE REDUCES THE DAMAGE BY 40%.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (48, 48, 1, 'img/skill/Deadly_Poison.png', 'DEADLY POISON', 'SPRAYS VENOM ON A RANDOM ENEMY, DEALING 450/750/1050 MAGIC DAMAGE EVERY SECOND AND REDUCING THE TARGET''S ATTACK SPEED BY 40/60/80 FOR 5S. THE ATTACK SPEED REDUCTION IGNORES ABILITY IMMUNITY.10/7/4 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (49, 49, 1, 'img/skill/Aurora.png', 'AURORA', 'CREATES A FIELD WITH A MAXIMUM RADIUS OF 3/4/5 GRIDS THAT SHRINKS UPON REACHING THE MAXIMUM SIZE. THE FIELD DEALS DAMAGE TO ENEMIES ONCE WHILE EXPANDING AND ONCE WHILE SHRINKING. ENEMIES FURTHER AWAY FROM THE HIM TAKE MORE DAMAGE (30-300/600/900).14/12/10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (50, 50, 1, 'img/skill/Void_Meteor.png', 'VOID METEOR', 'DEALS TRUE DAMAGE EQUAL TO 5%/7%/9% OF THEIR MAX HEALTH EVERY SECOND TO ENEMIES WITHIN 4 GRIDS FOR A TOTAL OF 10S.20 SECONDS COOLDOWN', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (51, 51, 2, 'img/skill/Voodoo.png', 'VOODOO', 'FIRES PARALYZING VENOM AT A RANDOM ENEMY. THE VENOM BOUNCES BETWEEN ENEMIES FOR A TOTAL 2/4/6 TIMES, WITH EACH BOUNCE DEALING 150/225/300 MAGIC DAMAGE AND STUNNING THE TARGET FOR 1S.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (52, 52, 1, 'img/skill/Transformation.png', 'TRANSFORMATION', 'TRANSFORMS INTO A WOLF, INCREASING MAXIMUM HEALTH BY 20%/30%/40%. ALSO SUMMONS 1 WOLF SPIRIT WITH 300/400/550 ATTACK DAMAGE AND 2000/3000/4500 HEALTH TO FIGHT ENEMIES.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (53, 53, 5, 'img/skill/Shared_Life.png', 'SHARED LIFE', 'SUMMONS A TOTEM TO HEAL HERSELF AND ALLIES FOR 225/300/375 EVERY 1.5S WITHIN 4 GRIDS. HEALING IS DISTRIBUTED EVENLY AMONG ALL TARGETS.15 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL
   (HERO_SKILL_ID, HERO_ID, HERO_SKILL_TYPE_ID, HERO_SKILL_ICON, HERO_SKILL_NAME, HERO_SKILL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (54, 54, 1, 'img/skill/Whirlwind.png', 'WHIRLWIND', 'SPINS THE IRON STAFF RAPIDLY, DEALING 150/300/450 MAGIC DAMAGE PER SECOND TO ENEMIES WITHIN 2 GRIDS. DISPELS ALL LOW-LEVEL DEBUFFS AND GAINS ABILITY IMMUNITY FOR 5S. INCREASES DAMAGE DONE BY 33% WHEN ATTACKING A SINGLE TARGET.10 SECONDS COOLDOWN.', TO_DATE('10/06/2019 16:55:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
