SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO
--
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (1, 'BANGAR', 'A', 1, 1, 5, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (2, 'BERSERKER', 'A', 2, 4, 6, 1, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (3, 'BIONIC NINJA', 'A', 3, 1, 4, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (4, 'CALAMITY', 'A', 4, 3, 7, 4, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (5, 'DRAGOON', 'A', 5, 4, 1, 11, 4, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (6, 'EVERBLOOM', 'A', 6, 2, 2, 8, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (7, 'EVERGREEN', 'A', 7, 2, 2, 8, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (8, 'FAMINE', 'A', 8, 1, 7, 5, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (9, 'FIREFUR', 'A', 9, 2, 5, 5, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (10, 'FLAMECALLER', 'A', 10, 3, 1, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (11, 'FORESTS BREATH', 'A', 11, 3, 2, 5, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (12, 'FROST LOTUS', 'A', 12, 1, 1, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (13, 'GENERAL PUFFER', 'A', 13, 2, 9, 1, 9, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (14, 'GENERAL OF WAR', 'A', 14, 4, 1, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (15, 'GLUTTON', 'A', 15, 2, 7, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (16, 'GROUNDSMASHER', 'A', 16, 2, 4, 7, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (17, 'GURRU', 'A', 17, 4, 12, 8, 0, 0, 0, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (18, 'HEADREAPER', 'A', 18, 4, 6, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (19, 'HOG RIDER', 'A', 19, 1, 6, 4, 5, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (20, 'HORNED MENACE', 'A', 20, 3, 3, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (21, 'ICETUSK', 'A', 21, 1, 3, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (22, 'KING OF THE SEA - SHAKARAKA', 'A', 22, 5, 9, 5, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (23, 'KRAKEN', 'A', 23, 4, 9, 5, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (24, 'LIGHTBRINGER', 'A', 24, 4, 1, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (25, 'LILITH', 'A', 25, 2, 8, 2, 9, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (26, 'MARSHLORD', 'A', 26, 2, 3, 6, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (27, 'MISFORTUNE', 'A', 27, 4, 7, 6, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (28, 'MISS SUPERSONIC', 'A', 28, 1, 4, 7, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (29, 'MOONLIGHT DRAGON', 'A', 29, 2, 2, 11, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (30, 'NETHER PRINCE', 'A', 30, 3, 8, 6, 9, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (31, 'NIGHTINGALE', 'A', 31, 1, 2, 9, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (32, 'NIGHTOWL', 'A', 32, 4, 3, 8, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (33, 'SCOURGE', 'A', 33, 2, 8, 4, 9, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (34, 'SIREN', 'A', 34, 3, 9, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (35, 'STALKER DRONE S90', 'A', 35, 3, 4, 5, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (36, 'STARHORN', 'A', 36, 4, 5, 3, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (37, 'STEELFIST', 'A', 37, 1, 4, 7, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (38, 'STINGER', 'A', 38, 3, 2, 7, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (39, 'SWORD DANCER', 'A', 39, 5, 2, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (40, 'TEMPLAR KNIGHT', 'A', 40, 3, 1, 4, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (41, 'TERMINATER - T3000', 'A', 41, 5, 4, 7, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (42, 'THE DARK MAGE -APOCALYPSE', 'A', 42, 5, 7, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (43, 'THE DEVOURER', 'A', 43, 3, 8, 9, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (44, 'THE EXECUTIONER', 'A', 44, 4, 8, 1, 9, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (45, 'THE ULTIMATE WEAPON - JOEY', 'A', 45, 5, 4, 7, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (46, 'TOTEMFACE', 'N', 46, 1, 6, 3, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (47, 'WOLF CAVALIER', 'A', 47, 2, 2, 4, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (48, 'VENOM', 'A', 48, 3, 3, 11, 2, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (49, 'VOID DESTRUCTION', 'A', 49, 3, 10, 3, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (50, 'VOID DOOM - NEBULA', 'A', 50, 5, 10, 6, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (51, 'VOODOO ELDER', 'A', 51, 2, 6, 6, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (52, 'WEREWOLF', 'A', 52, 3, 1, 3, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (53, 'WITCH DOCTOR', 'A', 53, 1, 3, 8, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE)
 Values
   (54, 'WUKONG', 'A', 54, 2, 5, 1, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
