SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_CLASS_DEL
--
Insert into USER_CHESSRUSH.CR_HERO_CLASS_DEL
   (CLASS_ID, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (5, 'HUNTER', 'HUNTERS CAN INCREASE ATTACK DAMAGE OF ALLY HUNTERS BY A SPECIFIC NUMBER.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/26/2019 06:28:20', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE SYNERGY DESCRIPTION');
COMMIT;
