SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_DEL
--
Insert into USER_CHESSRUSH.CR_HERO_DEL
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (18, 'HEAD REAPER', 'A', 18, 3, 6, 0, 2, 0, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/26/2019 06:20:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE TIER HERO');
Insert into USER_CHESSRUSH.CR_HERO_DEL
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, RACE_ID_ALT, CLASS_ID, CLASS_ID_ALT, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (39, 'SWORD DANCER', 'A', 39, 4, 2, 0, 2, 0, 1, 2, 3, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/26/2019 06:20:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE TIER HERO');
Insert into USER_CHESSRUSH.CR_HERO_DEL
   (HERO_ID, HERO_NAME, HERO_STATUS_CODE, HERO_TAGLINE_ID, HERO_TIER_ID, RACE_ID, CLASS_ID, ITEM_ID_REC_1, ITEM_ID_REC_2, ITEM_ID_REC_3, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (47, 'UNICORN CAVALIER', 'A', 47, 2, 2, 4, 6, 5, 4, TO_DATE('10/06/2019 16:41:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/27/2019 09:42:38', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE NAME');
COMMIT;
