SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_STATUS
--
Insert into USER_CHESSRUSH.CR_HERO_STATUS
   (HERO_STATUS_CODE, HERO_STATUS_NAME, DATE_CREATE, USER_CREATE)
 Values
   ('A', 'ACTIVE', TO_DATE('10/06/2019 17:29:36', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_STATUS
   (HERO_STATUS_CODE, HERO_STATUS_NAME, DATE_CREATE, USER_CREATE)
 Values
   ('N', 'NOT ACTIVE', TO_DATE('10/06/2019 17:29:36', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
