SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_RACE
--
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (1, 'img/race/Human_icon.jpg', 'HUMAN', 'HUMANS CAN RESTORE MP EVERY SECOND FOR ALL ALLIES, OR A CHANCE TO RESET THE ABILITY`S COOLDOWN AND RESTORE MANA.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (2, 'img/race/Elf_icon.jpg', 'ELF', 'ELF CAN GRANT ALLY ELVES A CHANCE TO DODGE ATTACKS', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (3, 'img/race/Beast_icon.jpg', 'BEAST', 'BEASTS CAN INCREASE A DAMAGE AND CHANCE TO SUMMON A PET.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (4, 'img/race/Cyborg_icon.jpg', 'CYBORG', 'CYBORGS CAN INCREASE A RANDOM ALLY OR AN ALLY CYBORG''S ARMOUR AND HEALTH REGENERATION.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (5, 'img/race/Furry_icon.jpg', 'FURRY', 'FURRY CAN RECEIVE A SHIELD THAT ABSORBS DAMAGE.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (6, 'img/race/Goblin_icon.jpg', 'GOBLIN', 'GOBLIN CAN GIVE ATTACK SPEED.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (7, 'img/race/Undead_icon.jpg', 'UNDEAD', 'UNDEAD CAN REDUCE THE ARMOUR OF ENEMIES.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (8, 'img/race/Demon_icon.jpg', 'DEMON', 'SOLO DEMON INCREASE DAMAGE AND CAUSE TARGET TO TAKE MORE DAMAGE', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (9, 'img/race/Oceanborn_icon.jpg', 'OCEANBORN', 'OCEANBORNS INCREASE MAGIC RESISTANCE OR RECEIVE ABILITY IMMUNITY.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (10, 'img/race/Void_icon.jpg', 'VOID', 'VOIDS DECREASE ENEMY''S MAX HEALTH.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (11, 'img/race/Dragon_icon.jpg', 'DRAGON', 'DRAGONS RESTORE MANA.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_RACE
   (RACE_ID, RACE_IMAGE, RACE_NAME, RACE_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (12, 'img/race/Jelly_icon.jpg', 'JELLY', 'JELLY ACT LIKE A THIRD MEMBER OF A TEAM.', TO_DATE('10/06/2019 17:16:16', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
