SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_SKILL_TYPE
--
Insert into USER_CHESSRUSH.CR_HERO_SKILL_TYPE
   (SKILL_TYPE_ID, SKILL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (1, 'RAW DAMAGE', TO_DATE('10/06/2019 17:22:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL_TYPE
   (SKILL_TYPE_ID, SKILL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (2, 'CROWD CONTROL', TO_DATE('10/06/2019 17:22:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL_TYPE
   (SKILL_TYPE_ID, SKILL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (3, 'SHIELD', TO_DATE('10/06/2019 17:22:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL_TYPE
   (SKILL_TYPE_ID, SKILL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (4, 'FUSION', TO_DATE('10/06/2019 17:22:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_SKILL_TYPE
   (SKILL_TYPE_ID, SKILL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (5, 'HEAL', TO_DATE('10/26/2019 10:53:17', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
