SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_CLASS
--
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (1, 'img/class/Warrior_icon.jpg', 'WARRIOR', 'WARRIORS INCREASE DAMAGE OF ALL ALLY WARRIORS BY A SPECIFIC NUMBER DEPENDING ON THE NUMBER.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (2, 'img/class/Assassin_icon.jpg', 'ASSASSIN', 'ALLY ASSASSINS BECOME INVISIBLE AT THE BEGINNING OF THE BATTLE DEPENDING ON THE NUMBER OF ALLIES.  WHILE INVISIBLE, ASSASSINS PERFORM A CRITICAL HIT AND LOSE INVISIBILTY.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (3, 'img/class/Sorcerer_icon.jpg', 'SORCERER', 'SORCERERS REDUCES ENEMY MAGIC BY A SPECIFIC NUMBER DEPENDING ON THE NUMBER.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (4, 'img/class/Rider_icon.jpg', 'RIDER', 'RIDERS HAVE A CHANCE TO GET ARMOUR AND MAGIC RESISTANCE TO ALLY RIDERS.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (5, 'img/class/Hunter_icon.jpg', 'HUNTER', 'HUNTERS HAVE CHANCE TO INCREASE ATTACK SPEED OF ALLY HUNTERS BY A SPECIFIC NUMBER', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (6, 'img/class/Warlock_icon.jpg', 'WARLOCK', 'WARLOCKS CAN INCREASE THE LIFE STEAL EFFECT OF ALL ALLIES.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (7, 'img/class/Engineer_icon.jpg', 'ENGINEER', 'ENGINEERS CAN INCREASE HEALTH REGEN OF ALLY ENGINEERS.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (8, 'img/class/Druid_icon.jpg', 'DRUID', 'A SMALLER AMOUNT OF DRUIDS CAN BE COMBINED TO MAKE A BETTER VERSION. THEY ALSO RESTORE MANA.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_CLASS
   (CLASS_ID, CLASS_IMAGE, CLASS_NAME, CLASS_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (9, 'img/class/Punisher_icon.jpg', 'PUNISHER', 'PUNISHERS NEGATE ENEMY DEMONS AND EMPOWER FRIENDLY DEMONS.', TO_DATE('10/06/2019 17:18:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
