SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_TIER
--
Insert into USER_CHESSRUSH.CR_HERO_TIER
   (HERO_TIER_ID, HERO_TIER_NAME, MANA_CRYSTAL, DATE_CREATE, USER_CREATE)
 Values
   (1, 'COMMON', 1, TO_DATE('10/06/2019 17:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TIER
   (HERO_TIER_ID, HERO_TIER_NAME, MANA_CRYSTAL, DATE_CREATE, USER_CREATE)
 Values
   (2, 'UNCOMMON', 2, TO_DATE('10/06/2019 17:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TIER
   (HERO_TIER_ID, HERO_TIER_NAME, MANA_CRYSTAL, DATE_CREATE, USER_CREATE)
 Values
   (3, 'RARE', 3, TO_DATE('10/06/2019 17:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TIER
   (HERO_TIER_ID, HERO_TIER_NAME, MANA_CRYSTAL, DATE_CREATE, USER_CREATE)
 Values
   (4, 'MYTHIC', 4, TO_DATE('10/06/2019 17:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TIER
   (HERO_TIER_ID, HERO_TIER_NAME, MANA_CRYSTAL, DATE_CREATE, USER_CREATE)
 Values
   (5, 'LEGENDARY', 5, TO_DATE('10/06/2019 17:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
