SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_HERO_TAGLINE
--
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, HERO_TAGLINE_WINNING, DATE_CREATE, USER_CREATE)
 Values
   (1, 'LET THE HUNTS BEGIN', 'HUNTS COMPLETE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (2, 'LET ME CLEAR OF PART OF BLOODS', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (3, 'MY SWORD IS COMBINATION AS STRENGTH AND DECISION', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (4, 'WHO''S THAT SUMMONING ME?', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (5, 'I WILL LEAD THE WAY TO VICTORY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (6, 'YOU REALLY THINK I CAN DO THIS?', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (7, 'I AM A MOUNTAIN', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (8, 'I THANK YOU FOR THIS OPPORTUNITY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (9, 'WE BETTER GET THE GOOD PRICE OF PREY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (10, 'I''M IN THE MOOD OF SOME BARBEQUE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, HERO_TAGLINE_WINNING, DATE_CREATE, USER_CREATE)
 Values
   (11, 'THIS TACTIC IS MY STYLE', 'I''M THE BEST HUNTER IN THE WORLD', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (12, 'YOU MADE THE RIGHT CHOICE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (13, 'I''M LOOKING FOR THE FIGHT', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (14, 'VICTORY IS WITHIN THE GRASP', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (15, 'VENGEANCE !!! VENGEANCE !!!', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (16, 'THEY CALLED ME THE MACHINEKILLER, BUT I AM REALLY JUST AN ESCAVATOR', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (17, 'GULLUU !!! GULLUU !!', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (18, 'YOU STRETCH MY BACK, I STRETCH YOURS', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (19, 'CHARGE!!! ', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (20, 'I BRING FEAR TO MY ENEMIES', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (21, 'I CAME ALONG WITH NORTHEN WIND', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (22, 'I SMELL OF BLOOD, THE BLOOD OF BATTLE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (23, 'DON''T LOOK THE BEAUTY FOR TOO LONG OR YOU NEVER BE ABLE TO LOOK AWAY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (24, 'WATCH MY BACK. LET''S PUT AN END TO THIS.', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (25, 'PLEASE BETTER HIDE SOMEWHERE, I CAN''T FIND', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (26, 'YOUNG PEOPLE HAVE NO RESPECT THIS DAY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (27, 'THE SHADOW GET THIS LIFE AND THE SHADOW TAKE IT AWAY', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (28, 'LET''S MAKE SOMETHING CREATIVE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (29, 'I AM A WITCH DRAGON', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (30, 'THE FLOWER OF DEATH WILL BLOOM', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (31, 'HMM I SMELL MAGIC', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (32, 'I WOULD AIDED COMPANION OF EVOLUTION', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (33, 'THEY MUST BE TEMPER WITCH', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (34, 'DEEP SEA CREAMY DOWNS HERE', TO_DATE('10/06/2019 16:47:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (35, 'CLICK !!! BATTLE S90 IS READY TO ENGAGE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (36, 'SSSST!! PLEASE BE QUITE WHEN I''M DEFINING THE FUTURE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (37, 'ORDER RECEIVED!!', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (38, 'ONE SLASH ONE KILL', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (39, 'I DART THE SHARPEST TIP OF BLADE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (40, 'STAY BEHIND ME', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (41, 'BATTLE MACHINE T3000 COMING ON STAGE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (42, 'HOW DARES TO WAKE ME UP', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (43, 'WHAT''S YOU TRULY LIKE? IS THAT THE EVIL ME?', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (44, 'I COME TO BRING HELL TO EARTH', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (45, 'I MADE STEP TWICE IN THE SAME RIVER', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (46, 'I AM RESPECTED IN MY VILLAGE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (47, 'LET MY BLADE DODGE  IN THE WIND', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (48, 'LET THEM EXPERIENCE THE PAIN THAT I SUFFERED', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (49, 'LONELY CREATURE LIKE YOU WILL FADE BEFORE THE POP SOFT OF THE VOID', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (50, 'LEARN TO THE DUSK IN THE VORTEX OF THE VOID', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (51, 'ALRIGHT!! ALRIGHT YO CALL THE SHOTS', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (52, 'I''M NOT FIGHTING ALONE', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (53, 'WITCH MEDICAL WORTH TO ME', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_HERO_TAGLINE
   (HERO_TAGLINE_ID, HERO_TAGLINE_ENTRANCE, DATE_CREATE, USER_CREATE)
 Values
   (54, 'DON''T EVEN TRY TO BRIBE ME WITH JUST ONE BANANA. HMM, SMELLS NICE.', TO_DATE('10/06/2019 16:47:14', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
