SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
--
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (61, 43, 5, 'BECOME INVINCIBLE FOR 3S WHEN HP DROPS BELOW 10%', TO_DATE('11/10/2019 21:40:07', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, 1, 'INCREASES ATTACK SPEED BY 20', TO_DATE('10/06/2019 18:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (2, 2, 1, 'INCREASES ATTACK DAMAGE BY 85', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (3, 3, 1, 'INCREASES MANA RECOVERED BY 50% WHEN DEALING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (4, 4, 1, 'INCREASES MANA RECOVERED BY 50% WHEN TAKING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (5, 5, 1, 'INCREASES MAGIC RESISTANCE BY 20', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (6, 6, 1, 'INCREASES ARMOR BY 20', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (7, 1, 2, 'INCREASES ATTACK SPEED BY 35', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (8, 2, 2, 'INCREASES ATTACK DAMAGE BY 115', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (9, 3, 2, 'INCREASES MANA RECOVERED BY 75% WHEN DEALING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (10, 4, 2, 'INCREASES MANA RECOVERED BY 75% WHEN TAKING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (11, 5, 2, 'INCREASES MAGIC RESISTANCE BY 30', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (12, 6, 2, 'INCREASES ARMOR BY 30', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (13, 1, 3, 'INCREASES ATTACK SPEED BY 50', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (14, 2, 3, 'INCREASES ATTACK DAMAGE BY 150', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (15, 3, 3, 'INCREASES MANA RECOVERED BY 100% WHEN DEALING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (16, 4, 3, 'INCREASES MANA RECOVERED BY 100% WHEN TAKING DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (17, 5, 3, 'INCREASES MAGIC RESISTANCE BY 50', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (18, 6, 3, 'INCREASES ARMOR BY 50', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (19, 1, 4, 'HAS A 30% CHANCE TO DEAL 250% MAGIC DAMAGE TO TARGET AND ENEMIES WITHIN 2 GRID OF THE TARGET', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (20, 2, 4, 'HAS A 30% CHANCE TO DEAL 200% DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (21, 3, 4, '1 NORMAL ATTACK DEALS 100 MAGIC DAMAGE FOR 5S AFTER CASTING ABILITY', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (22, 4, 4, 'GAINS A SHIELD WITH 20% OF MAX HEALTH UPON USING AN ABILITY', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (23, 5, 4, 'HAS A CHANCE TO REFLECT 30% OF MAGIC DAMAGE', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (24, 6, 4, 'SLOWS ATTACKER ATTACK SPEED BY 30% UPON TAKING DAMAGE FROM BASIC ATTACK', TO_DATE('10/06/2019 18:02:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (25, 7, 3, 'BLOCK 30 PHYSICAL DAMAGE', TO_DATE('11/10/2019 10:26:43', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (26, 8, 3, 'INCREASE MAX HP BY 750 ALSO RESTORES 40 HP EVERY SECOND', TO_DATE('11/10/2019 10:45:59', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (27, 9, 3, 'SILENCE A RANDOM ENEMY FOR 8S AT THE BEGINNING OF A BATTLE', TO_DATE('11/10/2019 10:46:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (28, 10, 3, 'INCREASE ATTACK DAMAGE BY 50 AND GAINS 15% LIFE STEAL', TO_DATE('11/10/2019 10:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (29, 11, 3, 'ATTACKS THE ENEMY WITH THE LOWEST HP FIRST, DEALING PHYSICAL DAMAGE EQUAL TO 5% OF HP LOST', TO_DATE('11/10/2019 10:50:50', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (30, 12, 3, 'INCREASE ATTACK SPEED BY 20. EACH ATTACK REDUCE TARGETS MANA BY 30', TO_DATE('11/10/2019 10:52:42', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (31, 13, 4, 'GAINS ASSASSIN', TO_DATE('11/10/2019 10:53:29', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (32, 14, 5, 'INCREASE DAMAGE DONE BY 10% FOR EVERY 10% HP LOST', TO_DATE('11/10/2019 10:54:39', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (33, 15, 4, 'INCREASE MAX HP BY 1000. GAINS A SHILD WITH 2000 HP WHEN HP DROPS BELOW 30%', TO_DATE('11/10/2019 10:55:58', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (34, 16, 4, 'INCREASE ATTACK DAMAGE BY 150. MELEE ATTACKS HAVE A 25% CHANCE OF TRIGGERING MOONBLADE AURA, DEALING MAGIC DAMAGE EQUAL TO 50% OF ATTACK DAMAGE TO ENEMIES IN ITS PATH. COOLDOWN 1S', TO_DATE('11/10/2019 11:02:53', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (35, 17, 5, 'GAINS RIDER', TO_DATE('11/10/2019 11:03:48', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (36, 18, 5, 'REDUCE MANA COST OF ABILITIES BY 50%. REDUCE COOLDOWN BY 1S WHEN ABILITY KILLS TARGET', TO_DATE('11/10/2019 11:08:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (37, 19, 5, 'INCREASE MAX HP BY 1000 AT THE BEGINNING OF BATTLE, SUMMKONS A CLONE WITH 50% OF ATTACK DAMAGE AND HP TO ASSIST IN A BATTLE', TO_DATE('11/10/2019 11:11:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (38, 20, 3, 'IF THERE ARE NO ALLIES WITHIN 1 SQUARES AT THE BEGINNING OF A BATTLE, GAINS 40 ARMOR AND A SHIELD WITH 30% OF MAX HP', TO_DATE('11/10/2019 11:13:08', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (39, 21, 3, 'INCREASE ALL DAMAGE DONE BY 10% AND REDUCE TARGETS MAGIC RESIST BY 25% FOR 10S', TO_DATE('11/10/2019 11:16:55', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (40, 22, 3, 'REDUCE ABILITY COOLDOWN BY 50%', TO_DATE('11/10/2019 11:18:59', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (41, 23, 4, 'INCREASES MAGIC RESIST BY 30%. 25% CHANCE TO BLOCK ABILITY DAMAGE', TO_DATE('11/10/2019 11:20:25', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (42, 24, 4, 'GAINS WARRIOR', TO_DATE('11/10/2019 11:21:03', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (43, 25, 4, 'EACH ATTCK STEAL 10 MANA FROM TARGET. ONCE MANA STOLEN REACHES 50, RESTORE 30 MANA TO ALL ALLIES WITHIN 1 SQUARES (ONLY TRIGGERS ONCE PER MATCH', TO_DATE('11/10/2019 11:26:26', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (44, 26, 5, 'REVIVES 3S AFTER DEATH AND RECOVERS 30% OF MAX HP', TO_DATE('11/10/2019 11:35:21', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (45, 27, 4, 'UPON DEALING DAMAGE, REDUCES TARGETS HEALING BY 60 FOR 5S', TO_DATE('11/10/2019 16:08:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (46, 28, 4, 'INCREASE ATTACK SPEED BY 30. EACH ATTACK INCREASES ATTACK DAMAGE BY 25 AND ARMOR PENETRATION BY 5%. THIS EFFECT RESET UPON REACHING 10 STACKS', TO_DATE('11/10/2019 16:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (47, 29, 4, 'CHANGE RACE TO DEMON', TO_DATE('11/10/2019 17:16:38', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (48, 30, 4, 'INCREASE ATTACK DAMAGE BY 200. ATTACK CAN''T BE DODGED', TO_DATE('11/10/2019 17:24:59', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (49, 31, 4, 'GAINS 60 ARMOR AND DEALS 100 MAGIC DAMAGE TO ALL ENEMIES WITHIN 1 SQUARES EVERY SECOND', TO_DATE('11/10/2019 17:28:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (50, 32, 5, 'CHANGE RACE TO DRAGON', TO_DATE('11/10/2019 17:33:15', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (51, 33, 4, 'INCREASE ATTACK DAMAGE BY 150. ATTACK HAVE A 25% CHANCE TO FREEZING TARGET FOR 2S', TO_DATE('11/10/2019 17:37:05', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (52, 34, 5, 'REDUCE DAMAGE TAKEN BY 10%. FOR EVERY ENEMY WITHIN 1 SQUARES, FURTHER REDUCE DAMAGE TAKEN BY 10% (UP TO 50%)', TO_DATE('11/10/2019 18:19:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (53, 35, 5, 'SUMMONS NIGHTOWL SPIRIT DO FIGHT ENEMIES AT THE BEGINNING OF BATTLE', TO_DATE('11/10/2019 19:10:11', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (54, 36, 5, 'INCREASE MAX HP BY 3000. RECOVERS 1% OF MAX HP EVERY 0.5S', TO_DATE('11/10/2019 19:15:42', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (55, 37, 5, 'INCREASE ALL SUMMONED PETS ATTACK SPEED BY 30 AND GRANTS THEM A SHIELD WITH 400 HP', TO_DATE('11/10/2019 19:19:54', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (56, 38, 5, 'FREEZING RANDOM TARGET FOR 5S AT THE BEGINNING OF BATTLE', TO_DATE('11/10/2019 19:23:39', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (57, 39, 5, 'INCREASE ABILITY DAMAGE BY 25% FOR ALL ALLIES WITHIN 1 SQUARES', TO_DATE('11/10/2019 20:06:31', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (58, 40, 4, 'ABILITY IGNITED TARGET FOR 3S, DEALING MAGIC DAMAGE EQUAL TO 30% OF ABILITY DAMAGE', TO_DATE('11/10/2019 21:06:36', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (59, 41, 5, 'GAINS 10% LIFE STEAL. EACH ATTACK DEALS TRUE DAMAGE EQUAL TO 5% OF CURRENT HP', TO_DATE('11/10/2019 21:09:29', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM_STAT_DETAIL
   (ITEM_STAT_DETAIL_ID, ITEM_ID, ITEM_LEVEL, ITEM_LEVEL_DESCRIPTION, DATE_CREATE, USER_CREATE)
 Values
   (60, 42, 5, 'CHANGES RACE TO CYBORG', TO_DATE('11/10/2019 21:14:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
