SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_ITEM
--
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (43, 'img/item/Diamond_Barrier_icon.png', 'DIAMOND BARRIER', TO_DATE('11/10/2019 21:14:32', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (1, 'img/item/Shocking_Dagger_icon.png', 'SHOCKING DAGGER', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (2, 'img/item/Critical_Greatsword_icon.png', 'CRITICAL GREATSWORD', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (3, 'img/item/Spellbane_Staff_icon.png', 'SPELLBANE STAFF', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (4, 'img/item/Forbidden_Tome_icon.png', 'FORBIDDEN TOME', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (5, 'img/item/Resistance_Cloak_icon.png', 'RESISTANCE CLOAK', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (6, 'img/item/Defensive_Armor_icon.png', 'DEFENSIVE ARMOR', TO_DATE('10/06/2019 17:53:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (7, 'img/item/Veterans_Bracers_icon.png', 'VETERANS BRACERS', TO_DATE('11/10/2019 10:24:34', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (8, 'img/item/Rejuvenation_icon.png', 'REJUVENATION', TO_DATE('11/10/2019 10:24:58', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (9, 'img/item/Orb_Of_Silence_icon.png', 'ORB OF SILENCE', TO_DATE('11/10/2019 10:25:46', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (10, 'img/item/Fanatics_Charm_icon.png', 'FANATICS CHARM', TO_DATE('11/10/2019 10:47:23', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (11, 'img/item/Hawkeye_Scope_icon.png', 'HAWKEYE SCOPE', TO_DATE('11/10/2019 10:49:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (12, 'img/item/Vapor_Blade_icon.png', 'VAPOR BLADE', TO_DATE('11/10/2019 10:51:43', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (13, 'img/item/Agent_Emblem_icon.png', 'AGENT EMBLEM', TO_DATE('11/10/2019 10:53:07', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (14, 'img/item/Gladiators_Chain_icon.png', 'GLADIATORS CHAIN', TO_DATE('11/10/2019 10:53:49', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (15, 'img/item/First_Aid_Charm_icon.png', 'FIRST AID CHARM', TO_DATE('11/10/2019 10:54:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (16, 'img/item/Moonblade_icon.png', 'MOONBLADE', TO_DATE('11/10/2019 11:01:33', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (17, 'img/item/Magic_Carpet_icon.png', 'MAGIC CARPET', TO_DATE('11/10/2019 11:03:35', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (18, 'img/item/Zealots_Tome_icon.png', 'ZEALOTS TOME', TO_DATE('11/10/2019 11:07:43', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (19, 'img/item/Phantom_Mirror_icon.png', 'PHANTOM MIRROR', TO_DATE('11/10/2019 11:09:36', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (20, 'img/item/Lonewolf_Helmet_icon.png', 'LONEWOLF HELMET', TO_DATE('11/10/2019 11:12:28', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (21, 'img/item/Dissolving_Staff_icon.png', 'DISSOLVING STAFF', TO_DATE('11/10/2019 11:15:22', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (22, 'img/item/Echo_Charm_icon.png', 'ECHO CHARM', TO_DATE('11/10/2019 11:18:31', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (23, 'img/item/Magician_Cape_icon.png', 'MAGICIAN CAPE', TO_DATE('11/10/2019 11:19:26', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (24, 'img/item/Gladiators_Dog_Tag_icon.png', 'GLADIATORS DOG TAG', TO_DATE('11/10/2019 11:20:46', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (25, 'img/item/Grim_Ring_icon.png', 'GRIM RING', TO_DATE('11/10/2019 11:23:46', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (26, 'img/item/Cloak_Of_The_Phoenix_icon.png', 'CLOAK OF THE PHOENIX', TO_DATE('11/10/2019 11:34:35', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (27, 'img/item/Cursed_Puppet_icon.png', 'CURSED PUPPET', TO_DATE('11/10/2019 16:07:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (28, 'img/item/Storm_Strike_icon.png', 'STORM STRIKE', TO_DATE('11/10/2019 16:11:17', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (29, 'img/item/Demon_Horn_icon.png', 'DEMON HORN', TO_DATE('11/10/2019 17:16:02', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (30, 'img/item/Corrosive__Blade_icon.png', 'CORROSIVE  BLADE', TO_DATE('11/10/2019 17:24:27', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (31, 'img/item/Spellfire_Armor_icon.png', 'SPELLFIRE ARMOR', TO_DATE('11/10/2019 17:27:53', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (32, 'img/item/Dragon_Blood_icon.png', 'DRAGON BLOOD', TO_DATE('11/10/2019 17:32:49', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (33, 'img/item/Frost_Hammer_icon.png', 'FROST HAMMER', TO_DATE('11/10/2019 17:35:32', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (34, 'img/item/Warbringers_Armor_icon.png', 'WARBRINGERS ARMOR', TO_DATE('11/10/2019 18:17:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (35, 'img/item/Spirit_Scroll_icon.png', 'SPIRIT SCROLL', TO_DATE('11/10/2019 19:09:15', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (36, 'img/item/Source_Of_Life_icon.png', 'SOURCE OF LIFE', TO_DATE('11/10/2019 19:14:40', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (37, 'img/item/Book_Of_Familiar_Spirit_icon.png', 'BOOK OF FAMILIAR SPIRIT', TO_DATE('11/10/2019 19:18:38', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (38, 'img/item/Freezing_Crystal_icon.png', 'FREEZING CRYSTAL', TO_DATE('11/10/2019 19:22:59', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (39, 'img/item/Glory_Grail_icon.png', 'GLORY GRAIL', TO_DATE('11/10/2019 20:05:44', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (40, 'img/item/Blazing_Edge_icon.png', 'BLAZING EDGE', TO_DATE('11/10/2019 21:05:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (41, 'img/item/Vampires_Fang_icon.png', 'VAMPIRES FANG', TO_DATE('11/10/2019 21:09:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_ITEM
   (ITEM_ID, ITEM_ICON, ITEM_NAME, DATE_CREATE, USER_CREATE)
 Values
   (42, 'img/item/Cyborg_Armor_icon.png', 'CYBORG ARMOR', TO_DATE('11/10/2019 21:14:32', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
