SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_LEVEL
--
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, 2, 2, TO_DATE('10/27/2019 18:24:33', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (2, 1, 3, 2, TO_DATE('10/27/2019 18:24:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (3, 1, 4, 5, TO_DATE('10/27/2019 18:25:13', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (4, 1, 5, 10, TO_DATE('10/27/2019 18:25:31', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (5, 1, 6, 15, TO_DATE('10/27/2019 18:25:47', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (6, 1, 7, 25, TO_DATE('10/27/2019 18:25:57', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (7, 1, 8, 40, TO_DATE('10/27/2019 18:26:28', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (8, 1, 9, 50, TO_DATE('10/27/2019 18:26:43', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (9, 1, 10, 0, TO_DATE('10/27/2019 18:27:24', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (10, 2, 2, 2, TO_DATE('10/27/2019 19:19:52', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (11, 2, 3, 2, TO_DATE('10/27/2019 19:20:36', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (12, 2, 4, 4, TO_DATE('10/27/2019 19:20:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (13, 2, 5, 8, TO_DATE('10/27/2019 19:21:05', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (14, 2, 6, 12, TO_DATE('10/27/2019 19:23:06', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (15, 2, 7, 20, TO_DATE('10/27/2019 19:25:24', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (16, 2, 8, 28, TO_DATE('10/27/2019 19:25:31', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (17, 2, 9, 40, TO_DATE('10/27/2019 19:27:31', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL
   (LEVEL_ID, LEVEL_TYPE_ID, LEVEL_NO, NEXT_LEVEL_EXP, DATE_CREATE, USER_CREATE)
 Values
   (18, 2, 10, 0, TO_DATE('10/27/2019 19:27:37', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
