SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_LEVEL_TYPE
--
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (1, 'CLASSIC MODE', TO_DATE('10/27/2019 18:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (2, 'TURBO MODE', TO_DATE('10/27/2019 18:38:07', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (3, 'SQUAD CLASH', TO_DATE('10/27/2019 18:39:44', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (4, 'CO-OP MODE', TO_DATE('10/27/2019 18:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (5, 'TREASURE RIDER', TO_DATE('10/27/2019 18:40:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (6, 'GOLD ARENA CHALLENGE', TO_DATE('10/27/2019 18:40:30', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (7, 'GOLD ARENA MASTER', TO_DATE('10/27/2019 18:41:03', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (8, 'PRACTICE', TO_DATE('10/27/2019 18:41:42', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (9, 'TUTORIAL', TO_DATE('10/27/2019 18:41:50', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_LEVEL_TYPE
   (LEVEL_TYPE_ID, LEVEL_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (10, 'BOT MODE', TO_DATE('10/27/2019 18:41:55', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
