SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_SYNERGY_EFFECT
--
Insert into USER_CHESSRUSH.CR_SYNERGY_EFFECT
   (SYNERGY_EFFECT_ID, SYNERGY_EFFECT_NAME, DATE_CREATE, USER_CREATE)
 Values
   (3, 'RACE ONLY', TO_DATE('11/08/2019 20:28:21', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_EFFECT
   (SYNERGY_EFFECT_ID, SYNERGY_EFFECT_NAME, DATE_CREATE, USER_CREATE)
 Values
   (1, 'ALLIES', TO_DATE('11/08/2019 20:27:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_EFFECT
   (SYNERGY_EFFECT_ID, SYNERGY_EFFECT_NAME, DATE_CREATE, USER_CREATE)
 Values
   (2, 'SINGLE ALLY', TO_DATE('11/08/2019 20:28:07', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_EFFECT
   (SYNERGY_EFFECT_ID, SYNERGY_EFFECT_NAME, DATE_CREATE, USER_CREATE)
 Values
   (4, 'CLASS ONLY', TO_DATE('11/08/2019 20:28:34', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_EFFECT
   (SYNERGY_EFFECT_ID, SYNERGY_EFFECT_NAME, DATE_CREATE, USER_CREATE)
 Values
   (5, 'ENEMIES', TO_DATE('11/08/2019 20:28:55', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
