SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_SYNERGY_DEL
--
Insert into USER_CHESSRUSH.CR_SYNERGY_DEL
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (33, '3 HUNTERS', 'INCREASES ATTACK DAMAGE OF ALLY HUNTERS BY 25%.', 'C', 5, 3, 0, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/26/2019 06:33:04', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE SNERGY BENEFIT');
Insert into USER_CHESSRUSH.CR_SYNERGY_DEL
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE, DATE_DELETE, USER_DELETE, REASON_DELETE)
 Values
   (34, '6 HUNTERS', 'INCREASES ATTACK DAMAGE OF ALLY HUNTERS BY 60%.', 'C', 5, 6, 0, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', TO_DATE('10/26/2019 06:33:04', 'MM/DD/YYYY HH24:MI:SS'), 'DBA', 'UPDATE SNERGY BENEFIT');
COMMIT;
