SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_SYNERGY_CODE
--
Insert into USER_CHESSRUSH.CR_SYNERGY_CODE
   (SYNERGY_CODE, SYNERGY_CODENAME, DATE_CREATE, USER_CREATE)
 Values
   ('C', 'CLASS', TO_DATE('10/06/2019 18:29:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_CODE
   (SYNERGY_CODE, SYNERGY_CODENAME, DATE_CREATE, USER_CREATE)
 Values
   ('R', 'RACE', TO_DATE('10/06/2019 18:29:01', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
