SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_SYNERGY_TYPE
--
Insert into USER_CHESSRUSH.CR_SYNERGY_TYPE
   (SYNERGY_TYPE_ID, SYNERGY_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (1, 'ATTACK', TO_DATE('10/06/2019 18:31:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_TYPE
   (SYNERGY_TYPE_ID, SYNERGY_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (2, 'DEFENSE', TO_DATE('10/06/2019 18:31:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY_TYPE
   (SYNERGY_TYPE_ID, SYNERGY_TYPE_NAME, DATE_CREATE, USER_CREATE)
 Values
   (3, 'SUPPORT', TO_DATE('10/06/2019 18:31:51', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
