SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM USER_CHESSRUSH.CR_SYNERGY
--
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (1, '2 HUMANS', 'RESTORE 3MP EVERY SECOND FOR ALL ALLIES', 'R', 0, 1, 2, 3, 1, TO_DATE('10/06/2019 18:26:09', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (2, '4 HUMANS', 'ALLY HUMANS HAVE 25% CHANCE TO RESET THE ABILITY`S COOLDOWN AND RESTORE 100 MANA AFTER CASTING AN ABILITY.', 'R', 0, 1, 4, 3, 3, TO_DATE('10/06/2019 18:26:09', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (3, '6 HUMANS', 'ALLY HUMANS HAVE 50% CHANCE TO RESET THE ABILITY''S COOLDOWN AND RESTORE 100 MANA AFTER CASTING AN ABILITY.', 'R', 0, 1, 6, 3, 3, TO_DATE('10/06/2019 18:26:09', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (4, '3 ELVES', 'GRANT ALLY ELVES A 25% CHANCE TO DODGE ATTACKS.', 'R', 0, 2, 3, 2, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (5, '6 ELVES', 'GRANT ALLY ELVES A 44% CHANCE TO DODGE ATTACKS.', 'R', 0, 2, 6, 2, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (6, '2 BEASTS', 'INCREASE ATTACK DAMAGE OF ALL ALLIES BY 10% (CAN BE INHERITED BY PETS SUMMONED)', 'R', 0, 3, 2, 1, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (7, '4 BEASTS', 'ALLIES HAVE A 40% CHANCE TO SUMMON A PET AT THE BEGINNING OF THE BATTLE.', 'R', 0, 3, 4, 1, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (8, '6 BEASTS', 'ALLIES HAVE A 60% CHANCE TO SUMMON A PET AT THE BEGINNING OF THE BATTLE.', 'R', 0, 3, 6, 1, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (9, '3 CYBORGS', 'INCREASE A RANDOM ALLY''S ARMOR BY 75 AND HEALTH REGENERATION BY 30', 'R', 0, 4, 3, 2, 2, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (10, '6 CYBORGS', 'INCEASE ALLY CYBORG''S ARMOR BY 75 AND HEALTH REGENERATION BY 30', 'R', 0, 4, 6, 2, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (11, '2 FURRIES', 'ALLY FURRIES RECEIVE A SHIELD THAT ABSORBS 800 DAMAGE.', 'R', 0, 5, 2, 2, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (12, '4 FURRIES', 'ALLY FURRIES RECEIVE A SHIELD THAT ABSORBS 2000 DAMAGE.', 'R', 0, 5, 4, 2, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (13, '2 GOBLINS', 'ATTACK SPEED +15% FOR ALL ALLIES; ATTACK SPEED +15% ADDITIONALLY FOR ALLY GOBLINS.', 'R', 0, 6, 2, 1, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (14, '4 GOBLINS', 'ATTACK SPEED +35% FOR ALL ALLIES; ATTACK SPEED +35% ADDITIONALLY FOR ALLY GOBLINS', 'R', 0, 6, 4, 1, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (15, '2 UNDEAD', 'REDUCES THE ARMOR OF ALL ENEMIES BY 20', 'R', 0, 7, 2, 1, 5, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (16, '4 UNDEAD', 'REDUCES THE ARMOR OF ALL ENEMIES BY 50', 'R', 0, 7, 4, 1, 5, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (17, '1 DEMON', 'WHEN YOU DEPLOY ONLY 1 DEMON, THEN ITS ATTACK DAMAGE IS INCREASED BY 40%. ITS ATTACK ALSO CAUSES ITS TARGET TO TAKE 10% MORE DAMAGE FOR 5 SECONDS.', 'R', 0, 8, 1, 1, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (18, '2 OCEANBORNS', 'INCREASE MAGIC RESISTANCE OF ALL ALLIES BY 20.', 'R', 0, 9, 2, 2, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (19, '4 OCEANBORNS', 'A RANDOM ALLY GAINS ABILITY IMMUNITY FOR 60 SECONDS.', 'R', 0, 9, 4, 2, 2, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (20, '2 VOIDS', 'DECREASES A RANDOM ENEMY''S MAX HEALTH BY 50%.', 'R', 0, 10, 2, 1, 5, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (21, '2 DRAGONS', 'RESTORE 30 MANA INSTANTLY AT THE BEGINNING OF THE BATTLE FOR ALLY DRAGONS.', 'R', 0, 11, 2, 3, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (22, '3 DRAGONS', 'RESTORE 100 MANA INSTANTLY AT THE BEGINNING OF THE BATTLE FOR ALLY DRAGONS.', 'R', 0, 11, 3, 3, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_AMOUNT, RACE_ID, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (23, '1 JELLY', 'WHEN YOU HAVE 2 IDENTICAL HEROES, YOU CAN DRAG GURRU WITH SAME STAR ON EITHER OF THEM TO COMBINE THEM INTO A HIGHER LEVEL HERO.', 'R', 0, 12, 1, 3, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (24, '3 WARRIORS', 'INCREASES ARMOR OF ALL ALLY WARRIORS BY 50', 'C', 1, 3, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (25, '6 WARRIORS', 'INCREASES ARMOR OF ALL ALLY WARRIORS BY 100.', 'C', 1, 6, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (26, '3 ASSASSINS', 'THEIR FIRST NORMAL ATTACK DEALS 250% DAMAGE, AND SUBSEQUENT ATTACKS HAVE A 10% CHANCE TO MAKE THEM INVISIBLE AGAIN.', 'C', 2, 3, 0, 1, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (27, '6 ASSASSINS', 'THEIR FIRST NORMAL ATTACK DEALS 250% DAMAGE, AND SUBSEQUENT ATTACKS HAVE A 25% CHANCE TO MAKE THEM INVISIBLE AGAIN.', 'C', 2, 6, 0, 1, 3, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (28, '3 SORCERERS', 'REDUCES ENEMY MAGIC RESISTANCE BY 20.', 'C', 3, 3, 0, 1, 5, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (29, '6 SORCERERS', 'REDUCES ENEMY MAGIC RESISTANCE BY 60.', 'C', 3, 6, 0, 1, 5, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (30, '2 RIDERS', '30% CHANCE TO GET 150 ARMOR AND 60% MAGIC RESISTANCE FOR ALLY RIDERS.', 'C', 4, 2, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (31, '4 RIDERS', '45% CHANCE TO GET 160 ARMOR AND 60% MAGIC RESISTANCE FOR ALLY RIDERS.', 'C', 4, 4, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (32, '6 RIDERS', '60% CHANCE TO GET 185 ARMOR AND 60% MAGIC RESISTANCE FOR ALLY RIDERS.', 'C', 4, 6, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (33, '3 HUNTERS', 'ALLY HUNTERS ATTACK HAVE A 20% CHANCE TO INCREASE ATTACK SPEED BY 100%', 'C', 5, 3, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (34, '6 HUNTERS', 'ALLY HUNTERS ATTACK HAVE A 60% CHANCE TO INCREASE ATTACK SPEED BY 100%', 'C', 5, 6, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (35, '2 WARLOCKS', 'INCREASES LIFE STEAL OF ALL ALLIES BY +15%. EXCESS HEALTH FROM LIFE STEAL BECOMES A SHIELD.', 'C', 6, 2, 0, 3, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (36, '4 WARLOCKS', 'INCREASES LIFE STEAL OF ALL ALLIES BY +25%. EXCESS HEALTH FROM LIFE STEAL BECOMES A SHIELD.', 'C', 6, 4, 0, 3, 1, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (37, '2 ENGINEERS', 'INCREASES HEALTH REGEN OF ALLY ENGINEERS BY 45.', 'C', 7, 2, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (38, '4 ENGINEERS', 'INCREASES HEALTH REGEN OF ALLY ENGINEERS BY 120.', 'C', 7, 4, 0, 2, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (39, '2 DRUIDS', '2 IDENTICAL 1-STAR DRUIDS CAN BE COMBINED TO A 2-STAR ONE INSTEAD OF 3. RESTORE 10 MANA FOR ALLIES WITHIN 1 GRID UPON DEATH.', 'C', 8, 2, 0, 3, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (40, '4 DRUIDS', '2 IDENTICAL 2-STAR DRUIDS CAN BE COMBINED TO A 3-STAR ONE INSTEAD OF 3. RESTORE 20 MANA FOR ALLIES WITHIN 1 GRID UPON DEATH.', 'C', 8, 4, 0, 3, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (41, '1 PUNISHERS', 'THE ALLY PUNISHER WILL BE TREATED AS AN ENEMY DEMON', 'C', 9, 1, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (42, '2 PUNISHERS', 'ALLY DEMONS ARE NOW TREATED AS PUNISHERS, BUT THEIR BONUS REMAINS.', 'C', 9, 2, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into USER_CHESSRUSH.CR_SYNERGY
   (SYNERGY_ID, SYNERGY_NAME, SYNERGY_BENEFIT, SYNERGY_CODE, CLASS_ID, CLASS_AMOUNT, RACE_AMOUNT, SYNERGY_TYPE_ID, SYNERGY_EFFECT_ID, DATE_CREATE, USER_CREATE)
 Values
   (43, '4 PUNISHERS', 'NORMAL ATTACKS DEAL 35% PHYSICAL DAMAGE TO UNITS AROUND (WITHIN 1 GRID) THE TARGET FOR ALLY PUNISHERS.', 'C', 9, 4, 0, 1, 4, TO_DATE('10/06/2019 18:26:10', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
