CREATE TABLE USER_CHESSRUSH.APP_ROLE_MENU_DEL
(
  ROLE_MENU_ID   NUMBER                         NOT NULL,
  ROLE_ID        NUMBER                         NOT NULL,
  MENU_ID        NUMBER                         NOT NULL,
  IS_SELECT      VARCHAR2(1 BYTE),
  DATE_CREATE    DATE                           DEFAULT SYSDATE,
  USER_CREATE    VARCHAR2(20 BYTE)              DEFAULT 'DBA',
  DATE_MODIFY    DATE,
  USER_MODIFY    VARCHAR2(20 BYTE),
  DATE_DELETE    DATE,
  USER_DELETE    VARCHAR2(20 BYTE),
  REASON_DELETE  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;