CREATE TABLE USER_CHESSRUSH.APP_ROLE
(
  ROLE_ID      NUMBER,
  ROLE_NAME    VARCHAR2(50 BYTE),
  ROLE_STATUS  VARCHAR2(1 BYTE)                 DEFAULT 'A',
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(20 BYTE)                DEFAULT 'DBA',
  DATE_MODIFY  DATE,
  USER_MODIFY  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;