CREATE TABLE USER_CHESSRUSH.APP_API_CLIENT
(
  CLIENT_ID             NUMBER,
  CLIENT_NAME           VARCHAR2(255 BYTE),
  CLIENT_BUSINESS_TYPE  VARCHAR2(100 BYTE),
  ACCESS_TYPE_ID        NUMBER,
  IS_ACTIVE             VARCHAR2(1 BYTE),
  DATE_CREATE           DATE                    DEFAULT SYSDATE,
  USER_CREATE           VARCHAR2(20 BYTE)       DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;