CREATE TABLE USER_CHESSRUSH.APP_STATISTIC_UNIQUE_HIT
(
  UNIQUE_HIT_ID      NUMBER,
  UNIQUE_DATE_HIT    DATE,
  UNIQUE_IP_ADDRESS  VARCHAR2(15 BYTE),
  COUNTRY            VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;