CREATE TABLE USER_CHESSRUSH.APP_USER_SESSION
(
  SESSION_ID      NUMBER                        NOT NULL,
  SESSION_START   NUMBER,
  SESSION_EXPIRE  NUMBER,
  USER_ID         NUMBER,
  IP_ADDRESS      VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;