CREATE TABLE USER_CHESSRUSH.APP_USER_ACTIVATION_LOG
(
  ACTIVATION_ID           NUMBER,
  USER_ID                 NUMBER,
  ACTIVATION_SENT_DATE    DATE,
  ACTIVATION_SENT_STATUS  VARCHAR2(3 BYTE),
  ACTIVATION_SENT_DESC    VARCHAR2(4000 BYTE),
  ACTIVATION_REC_DATE     DATE,
  ACTIVATION_REC_STATUS   VARCHAR2(3 BYTE),
  ACTIVATION_REC_DESC     VARCHAR2(4000 BYTE),
  ACTIVATION_STATUS       VARCHAR2(1 BYTE),
  DATE_CREATE             DATE                  DEFAULT SYSDATE,
  USER_CREATE             VARCHAR2(20 BYTE)     DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;