CREATE TABLE USER_CHESSRUSH.APP_MENU_DEL
(
  MENU_ID         NUMBER                        NOT NULL,
  MENU_NAME       VARCHAR2(50 BYTE),
  LINK            VARCHAR2(150 BYTE),
  SORT_NO         NUMBER,
  PARENT_MENU_ID  NUMBER,
  IS_CRUD         VARCHAR2(1 BYTE)              DEFAULT 'N',
  IS_NEW          VARCHAR2(1 BYTE)              DEFAULT 'Y',
  MENU_STATUS     VARCHAR2(1 BYTE)              DEFAULT 'A',
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(20 BYTE)             DEFAULT 'DBA',
  DATE_MODIFY     DATE,
  USER_MODIFY     VARCHAR2(20 BYTE),
  DATE_DELETE     DATE,
  USER_DELETE     VARCHAR2(20 BYTE),
  REASON_DELETE   VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;