CREATE TABLE USER_CHESSRUSH.APP_MESSAGE
(
  MESSAGE_ID   NUMBER,
  NAME         VARCHAR2(100 BYTE),
  EMAIL        VARCHAR2(255 BYTE),
  MESSAGE      VARCHAR2(4000 BYTE),
  IP_ADDRESS   VARCHAR2(15 BYTE),
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(50 BYTE)                DEFAULT 'ANONYMOUS'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;