CREATE TABLE USER_CHESSRUSH.APP_USER_INVALID_UNLOCK
(
  INVALID_UNLOCK_ID           NUMBER,
  INVALID_UNLOCK_DESCRIPTION  VARCHAR2(120 BYTE),
  DATE_CREATE                 DATE              DEFAULT SYSDATE,
  USER_CREATE                 VARCHAR2(50 BYTE) DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;