CREATE TABLE USER_CHESSRUSH.APP_ROLE_MENU
(
  ROLE_MENU_ID  NUMBER                          NOT NULL,
  ROLE_ID       NUMBER                          NOT NULL,
  MENU_ID       NUMBER                          NOT NULL,
  IS_SELECT     VARCHAR2(1 BYTE),
  DATE_CREATE   DATE                            DEFAULT SYSDATE,
  USER_CREATE   VARCHAR2(20 BYTE)               DEFAULT 'DBA',
  DATE_MODIFY   DATE,
  USER_MODIFY   VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;