CREATE TABLE USER_CHESSRUSH.APP_USER_LOG
(
  USERLOG_ID         NUMBER                     NOT NULL,
  USER_ID            NUMBER,
  IP_ADDRESS         VARCHAR2(20 BYTE),
  IS_LOGIN           VARCHAR2(1 BYTE),
  LAST_LOGIN         DATE,
  IS_LOGOUT          VARCHAR2(1 BYTE),
  LAST_LOGOUT        DATE,
  DATE_KICKER        DATE,
  USER_ID_KICKER     NUMBER,
  IP_ADDRESS_KICKER  VARCHAR2(15 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;