CREATE TABLE USER_CHESSRUSH.APP_API_ACCESS_DETAIL
(
  ACCESS_DETAIL_ID  NUMBER,
  ACCESS_ID         NUMBER,
  IP_ADDRESS        VARCHAR2(15 BYTE),
  IP_TYPE           VARCHAR2(4 BYTE),
  IS_ACTIVE         VARCHAR2(1 BYTE),
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(20 BYTE)           DEFAULT 'DBA',
  DATE_MODIFY       DATE,
  USER_DELETE       VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;