CREATE TABLE USER_CHESSRUSH.APP_ROLE_DEL
(
  ROLE_ID        NUMBER,
  ROLE_NAME      VARCHAR2(50 BYTE),
  ROLE_STATUS    VARCHAR2(1 BYTE)               DEFAULT 'A',
  DATE_CREATE    DATE                           DEFAULT SYSDATE,
  USER_CREATE    VARCHAR2(20 BYTE)              DEFAULT 'DBA',
  DATE_MODIFY    DATE,
  USER_MODIFY    VARCHAR2(20 BYTE),
  DATE_DELETE    DATE,
  USER_DELETE    VARCHAR2(20 BYTE),
  REASON_DELETE  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;