CREATE TABLE USER_CHESSRUSH.CR_BUILD_LIST_TMP
(
  BUILD_ID     NUMBER,
  BUILD_NAME   VARCHAR2(50 BYTE),
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(50 BYTE)                DEFAULT 'USER'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;