CREATE TABLE USER_CHESSRUSH.CR_BUILD_DETAIL_HERO_TMP
(
  BD_HERO_ID   NUMBER,
  BUILD_ID     NUMBER,
  HERO_ID      NUMBER,
  STAR_GRADE   NUMBER,
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(50 BYTE)                DEFAULT 'USER'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;