CREATE TABLE USER_CHESSRUSH.CR_HERO_TIER_DEL
(
  HERO_TIER_ID    NUMBER,
  HERO_TIER_NAME  VARCHAR2(50 BYTE),
  MANA_CRYSTAL    NUMBER,
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(50 BYTE)             DEFAULT 'DBA',
  DATE_DELETE     DATE                          DEFAULT SYSDATE,
  USER_DELETE     VARCHAR2(50 BYTE)             DEFAULT 'DBA',
  REASON_DELETE   VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;