CREATE TABLE USER_CHESSRUSH.CR_HERO_STAT
(
  HERO_STAT_ID   NUMBER,
  HERO_ID        NUMBER,
  STAR_GRADE     NUMBER,
  STAT_TYPE_ID   NUMBER,
  HEALTH_POINT   NUMBER,
  ARMOR_LEVEL    NUMBER,
  MAGIC_RESIST   NUMBER,
  ATTACK_DAMAGE  NUMBER,
  ATTACK_SPEED   NUMBER,
  ATTACK_RANGE   NUMBER,
  DATE_CREATE    DATE                           DEFAULT SYSDATE,
  USER_CREATE    VARCHAR2(50 BYTE)              DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;