CREATE TABLE USER_CHESSRUSH.CR_HERO
(
  HERO_ID           NUMBER,
  HERO_NAME         VARCHAR2(50 BYTE),
  HERO_STATUS_CODE  VARCHAR2(1 BYTE),
  HERO_TAGLINE_ID   NUMBER,
  HERO_TIER_ID      NUMBER,
  RACE_ID           NUMBER,
  RACE_ID_ALT       NUMBER,
  CLASS_ID          NUMBER,
  CLASS_ID_ALT      NUMBER,
  ITEM_ID_REC_1     NUMBER,
  ITEM_ID_REC_2     NUMBER,
  ITEM_ID_REC_3     NUMBER,
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(50 BYTE)           DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;