CREATE TABLE USER_CHESSRUSH.CR_HERO_STATUS_DEL
(
  HERO_STATUS_CODE  VARCHAR2(1 BYTE),
  HERO_STATUS_NAME  VARCHAR2(50 BYTE),
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(50 BYTE)           DEFAULT 'DBA',
  DATE_DELETE       DATE                        DEFAULT SYSDATE,
  USER_DELETE       VARCHAR2(50 BYTE)           DEFAULT 'DBA',
  REASON_DELETE     VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;