CREATE TABLE USER_CHESSRUSH.CR_HERO_STATUS
(
  HERO_STATUS_CODE  VARCHAR2(1 BYTE),
  HERO_STATUS_NAME  VARCHAR2(50 BYTE),
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(50 BYTE)           DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;