CREATE TABLE USER_CHESSRUSH.CR_HERO_STAT_TYPE
(
  STAT_TYPE_ID    NUMBER,
  STAT_TYPE_NAME  VARCHAR2(50 BYTE),
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(50 BYTE)             DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;