CREATE TABLE USER_CHESSRUSH.CR_HERO_SKILL_TYPE_DEL
(
  SKILL_TYPE_ID    NUMBER,
  SKILL_TYPE_NAME  VARCHAR2(50 BYTE),
  DATE_CREATE      DATE                         DEFAULT SYSDATE,
  USER_CREATE      VARCHAR2(50 BYTE)            DEFAULT 'DBA',
  DATE_DELETE      DATE                         DEFAULT SYSDATE,
  USER_DELETE      VARCHAR2(50 BYTE)            DEFAULT 'DBA',
  REASON_DELETE    VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;