CREATE TABLE USER_CHESSRUSH.CR_ITEM_STAT_DETAIL_DEL
(
  ITEM_STAT_DETAIL_ID     NUMBER,
  ITEM_ID                 NUMBER,
  ITEM_LEVEL              NUMBER,
  ITEM_LEVEL_DESCRIPTION  VARCHAR2(4000 BYTE),
  DATE_CREATE             DATE                  DEFAULT SYSDATE,
  USER_CREATE             VARCHAR2(50 BYTE)     DEFAULT 'DBA',
  DATE_DELETE             DATE                  DEFAULT SYSDATE,
  USER_DELETE             VARCHAR2(50 BYTE)     DEFAULT 'DBA',
  REASON_DELETE           VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;