CREATE TABLE USER_CHESSRUSH.CR_LEVEL
(
  LEVEL_ID        NUMBER,
  LEVEL_TYPE_ID   NUMBER,
  LEVEL_NO        NUMBER,
  NEXT_LEVEL_EXP  NUMBER,
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(50 BYTE)             DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;