CREATE TABLE USER_CHESSRUSH.CR_LEVEL_DEL
(
  LEVEL_ID        NUMBER,
  LEVEL_TYPE_ID   NUMBER,
  LEVEL_NO        NUMBER,
  NEXT_LEVEL_EXP  NUMBER,
  DATE_CREATE     DATE,
  USER_CREATE     VARCHAR2(50 BYTE),
  DATE_DELETE     DATE,
  USER_DELETE     VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;