CREATE TABLE USER_CHESSRUSH.CR_LEVEL_RARITY_DEL
(
  LEVEL_RARITY_ID     NUMBER,
  LEVEL_NO            NUMBER,
  HERO_TIER_1         NUMBER,
  HERO_TIER_CHANCE_1  NUMBER,
  HERO_TIER_2         NUMBER,
  HERO_TIER_CHANCE_2  NUMBER,
  HERO_TIER_3         NUMBER,
  HERO_TIER_CHANCE_3  NUMBER,
  HERO_TIER_4         NUMBER,
  HERO_TIER_CHANCE_4  NUMBER,
  HERO_TIER_5         NUMBER,
  HERO_TIER_CHANCE_5  NUMBER,
  DATE_CREATE         DATE                      DEFAULT SYSDATE,
  USER_CREATE         VARCHAR2(50 BYTE)         DEFAULT 'DBA',
  DATE_DELETE         DATE,
  USER_DELETE         VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;