CREATE TABLE USER_CHESSRUSH.CR_PREVIEW_BENCH
(
  SESSION_ID   NUMBER,
  SLOT_NO      NUMBER,
  HERO_ID      NUMBER,
  STAR_GRADE   NUMBER,
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(20 BYTE)                DEFAULT 'DBA',
  DATE_MODIFY  DATE,
  USER_MODIFY  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;