CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_CODE_DEL
(
  SYNERGY_CODE      VARCHAR2(1 BYTE),
  SYNERGY_CODENAME  VARCHAR2(5 BYTE),
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(50 BYTE)           DEFAULT 'DBA',
  DATE_DELETE       DATE                        DEFAULT SYSDATE,
  USER_DELETE       VARCHAR2(50 BYTE)           DEFAULT 'DBA',
  REASON_DELETE     VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;