CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_EFFECT_DEL
(
  SYNERGY_EFFECT_ID    NUMBER,
  SYNERGY_EFFECT_NAME  VARCHAR2(20 BYTE),
  DATE_CREATE          DATE                     DEFAULT SYSDATE,
  USER_CREATE          VARCHAR2(50 BYTE)        DEFAULT 'DBA',
  DATE_DELETE          DATE,
  USER_DELETE          VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;