CREATE TABLE USER_CHESSRUSH.CR_SAVE_BUILD_LIST_DEL
(
  SAVE_BUILD_LIST_ID  NUMBER,
  BUILD_ID            NUMBER,
  BUILD_NAME          VARCHAR2(50 BYTE),
  HERO_ID_1           NUMBER,
  HERO_ID_2           NUMBER,
  HERO_ID_3           NUMBER,
  HERO_ID_4           NUMBER,
  HERO_ID_5           NUMBER,
  HERO_ID_6           NUMBER,
  HERO_ID_7           NUMBER,
  HERO_ID_8           NUMBER,
  HERO_ID_9           NUMBER,
  HERO_ID_10          NUMBER,
  STAR_GRADE_1        NUMBER,
  STAR_GRADE_2        NUMBER,
  STAR_GRADE_3        NUMBER,
  STAR_GRADE_4        NUMBER,
  STAR_GRADE_5        NUMBER,
  STAR_GRADE_6        NUMBER,
  STAR_GRADE_7        NUMBER,
  STAR_GRADE_8        NUMBER,
  STAR_GRADE_9        NUMBER,
  STAR_GRADE_10       NUMBER,
  SYNERGY_ID_1        NUMBER,
  SYNERGY_ID_2        NUMBER,
  SYNERGY_ID_3        NUMBER,
  SYNERGY_ID_4        NUMBER,
  SYNERGY_ID_5        NUMBER,
  SYNERGY_ID_6        NUMBER,
  SYNERGY_ID_7        NUMBER,
  SYNERGY_ID_8        NUMBER,
  SYNERGY_ID_9        NUMBER,
  SYNERGY_ID_10       NUMBER,
  DATE_CREATE         DATE                      DEFAULT SYSDATE,
  USER_CREATE         VARCHAR2(50 BYTE)         DEFAULT 'USER',
  DATE_DELETE         DATE                      DEFAULT SYSDATE,
  USER_DELETE         VARCHAR2(50 BYTE)         DEFAULT 'USER',
  REASON_DELETE       VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;