CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_EFFECT
(
  SYNERGY_EFFECT_ID    NUMBER,
  SYNERGY_EFFECT_NAME  VARCHAR2(20 BYTE),
  DATE_CREATE          DATE                     DEFAULT SYSDATE,
  USER_CREATE          VARCHAR2(50 BYTE)        DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;