CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_CODE
(
  SYNERGY_CODE      VARCHAR2(1 BYTE),
  SYNERGY_CODENAME  VARCHAR2(5 BYTE),
  DATE_CREATE       DATE                        DEFAULT SYSDATE,
  USER_CREATE       VARCHAR2(50 BYTE)           DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;