CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_TYPE
(
  SYNERGY_TYPE_ID    NUMBER,
  SYNERGY_TYPE_NAME  VARCHAR2(10 BYTE),
  DATE_CREATE        DATE                       DEFAULT SYSDATE,
  USER_CREATE        VARCHAR2(50 BYTE)          DEFAULT 'DBA'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;