CREATE TABLE USER_CHESSRUSH.CR_SYNERGY_DEL
(
  SYNERGY_ID         NUMBER,
  SYNERGY_NAME       VARCHAR2(50 BYTE),
  SYNERGY_BENEFIT    VARCHAR2(4000 BYTE),
  SYNERGY_CODE       VARCHAR2(1 BYTE),
  CLASS_ID           NUMBER,
  CLASS_AMOUNT       NUMBER,
  RACE_ID            NUMBER,
  RACE_AMOUNT        NUMBER,
  SYNERGY_TYPE_ID    NUMBER,
  SYNERGY_EFFECT_ID  NUMBER,
  DATE_CREATE        DATE                       DEFAULT SYSDATE,
  USER_CREATE        VARCHAR2(50 BYTE)          DEFAULT 'DBA',
  DATE_DELETE        DATE,
  USER_DELETE        VARCHAR2(50 BYTE),
  REASON_DELETE      VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;