CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_HERO_SKILL_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_HERO_SKILL REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_HERO_SKILL_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.HERO_SKILL_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


