CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_BUILD_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_BUILD_LIST_TMP 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_BUILD_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.BUILD_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


