CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_APP_STATISTIC_HIT
BEFORE INSERT
ON USER_CHESSRUSH.APP_STATISTIC_HIT 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_HIT_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.HIT_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


