CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_SAVE_BUILD_LIST_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_SAVE_BUILD_LIST REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_SAVE_BUILD_LIST_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.SAVE_BUILD_LIST_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


