CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_APP_USER_ACTIVATION_LOG
   BEFORE INSERT
   ON USER_CHESSRUSH.APP_USER_ACTIVATION_LOG    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
DECLARE
   tmpVar   NUMBER;
BEGIN
   tmpVar := 0;

   SELECT   SQ_ACTIVATION_ID.NEXTVAL INTO tmpVar FROM DUAL;

   :NEW.ACTIVATION_ID := tmpVar;
EXCEPTION
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END;
/


