CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_BD_HERO_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_BUILD_DETAIL_HERO_TMP 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_BD_HERO_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.BD_HERO_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


