CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_ITEM_STAT_DETAIL_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_ITEM_STAT_DETAIL REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_ITEM_STAT_DETAIL_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ITEM_STAT_DETAIL_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


