CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_CR_SYNERGY_EFFECT
BEFORE INSERT
ON USER_CHESSRUSH.CR_SYNERGY_EFFECT 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_SYNERGY_EFFECT_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.SYNERGY_EFFECT_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


