CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_CLASS_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_HERO_CLASS REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_CLASS_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.CLASS_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


