CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_STAT_TYPE_ID
BEFORE INSERT
ON USER_CHESSRUSH.CR_HERO_STAT_TYPE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_STAT_TYPE_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.STAT_TYPE_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


