CREATE OR REPLACE TRIGGER USER_CHESSRUSH.TRG_APP_USER_INVALID_UNLOCK
BEFORE INSERT
ON USER_CHESSRUSH.APP_USER_INVALID_UNLOCK 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_INVALID_UNLOCK_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.INVALID_UNLOCK_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


