/* Formatted on 11/2/2019 5:06:05 AM (QP5 v5.114.809.3010) */
EXEC SP_UPD_SLOT_BENCH(2, 1, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 2, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 3, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 4, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 5, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 6, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 7, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
EXEC SP_UPD_SLOT_BENCH(2, 8, FLOOR(DBMS_RANDOM.VALUE(1,54)), FLOOR(DBMS_RANDOM.VALUE(1,3)), 'HURRICANOS');
