CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_APP_INS_STAT_HIT (P_IP_ADDRESS    VARCHAR2,
                                                 P_COUNTRY       VARCHAR2)
IS
   V_COUNT_IP   NUMBER;
BEGIN
   INSERT INTO APP_STATISTIC_HIT (DATE_HIT, IP_ADDRESS, COUNTRY)
     VALUES   (SYSDATE, P_IP_ADDRESS, P_COUNTRY);

   SP_APP_INS_STAT_UNIQUE_HIT (P_IP_ADDRESS, P_COUNTRY);

   COMMIT;
END;
/


