CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_APP_DEL_MENU (
   P_MENU_ID      NUMBER,
   P_USERLOGIN    VARCHAR2,
   P_REASON       VARCHAR2
)
IS
BEGIN
   INSERT INTO APP_MENU_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   APP_MENU A
       WHERE   A.MENU_ID = P_MENU_ID;

   DELETE FROM   APP_MENU
         WHERE   MENU_ID = P_MENU_ID;

   COMMIT;
END;
/


