CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_APP_INS_USER_ACTIVATION (
   P_USER_ID      NUMBER,
   P_USERLOGIN    VARCHAR2
)
IS
BEGIN
   INSERT INTO APP_USER_ACTIVATION_LOG (USER_ID, DATE_CREATE, USER_CREATE)
     VALUES   (P_USER_ID, SYSDATE, P_USERLOGIN);

   COMMIT;
END;
/


