CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_APP_UPD_USER (
   P_USER_ID      NUMBER,
   P_USER_NAME    VARCHAR2,
   P_PASSWORD     VARCHAR2,
   P_ROLE_ID      NUMBER,
   P_EMAIL        VARCHAR2,
   P_USERLOGIN    VARCHAR2
)
IS
BEGIN
   UPDATE   APP_USER
      SET   USER_NAME = P_USER_NAME,
            PASSWORD = P_PASSWORD,
            ROLE_ID = P_ROLE_ID,
            EMAIL = P_EMAIL,
            DATE_MODIFY = SYSDATE,
            USER_MODIFY = P_USERLOGIN
    WHERE   USER_ID = P_USER_ID;

   SP_APP_INS_USER_ACTIVATION (P_USER_ID, P_USERLOGIN);

   COMMIT;
END;
/


