CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_APP_UPD_USER_ACTIVATION (
   P_CODE           VARCHAR2,
   P_STATUS_CODE    VARCHAR2,
   P_STATUS_DESC    VARCHAR2,
   P_USER_ID        NUMBER
)
IS
BEGIN
   IF P_CODE = 'SENT'
   THEN
      UPDATE   APP_USER_ACTIVATION_LOG
         SET   ACTIVATION_SENT_DATE = SYSDATE,
               ACTIVATION_SENT_STATUS = P_STATUS_CODE,
               ACTIVATION_SENT_DESC = P_STATUS_DESC,
               ACTIVATION_STATUS = 'S'
       WHERE   USER_ID = P_USER_ID AND ACTIVATION_STATUS IS NULL;
   END IF;

   IF P_CODE = 'RECEIVE'
   THEN
      UPDATE   APP_USER_ACTIVATION_LOG
         SET   ACTIVATION_REC_DATE = SYSDATE,
               ACTIVATION_REC_STATUS = P_STATUS_CODE,
               ACTIVATION_REC_DESC = P_STATUS_DESC,
               ACTIVATION_STATUS = 'A'
       WHERE   USER_ID = P_USER_ID AND ACTIVATION_STATUS = 'S';

      UPDATE   APP_USER
         SET   USER_STATUS = 'A'
       WHERE   USER_ID = P_USER_ID;
   END IF;

   COMMIT;
END;
/


