CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_CRT_BUILD_TMP (
   P_BUILD_NAME    VARCHAR2,
   P_USERLOGIN     VARCHAR2
)
IS
BEGIN
   --DELETE OLD TEMPORARY BUILD
   SP_DEL_BUILD_TMP (P_USERLOGIN);

   --INSERT NEW TEMPORARY BUILD
   INSERT INTO CR_BUILD_LIST_TMP (BUILD_NAME, USER_CREATE)
     VALUES   (P_BUILD_NAME, P_USERLOGIN);

   COMMIT;
END;
/


