CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_CRT_SIMPLE_BUILD_TMP (
   P_BUILD_NAME    VARCHAR2,
   P_HERO_ID_1     NUMBER,
   P_HERO_ID_2     NUMBER,
   P_HERO_ID_3     NUMBER,
   P_HERO_ID_4     NUMBER,
   P_HERO_ID_5     NUMBER,
   P_HERO_ID_6     NUMBER,
   P_HERO_ID_7     NUMBER,
   P_HERO_ID_8     NUMBER,
   P_HERO_ID_9     NUMBER,
   P_HERO_ID_10    NUMBER,
   P_USERLOGIN     VARCHAR2
)
IS

V_BUILD_ID NUMBER;
V_STAR_GRADE NUMBER;

BEGIN
   --CREATE BUILD NAME
   SP_CRT_BUILD_TMP (P_BUILD_NAME, P_USERLOGIN);
   
   --TAKE THE BUILD_ID BY USER
   SELECT BUILD_ID INTO V_BUILD_ID FROM CR_BUILD_LIST_TMP WHERE USER_CREATE = P_USERLOGIN;
   
   --INSERT HERO ID AND STAR GRADE
   --FOR SIMPLIFY, JUST FILL THE DEFAULT VALUE OF STAR GRADE (3).
   V_STAR_GRADE := 3;
   
   IF P_HERO_ID_1 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_1, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_2 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_2, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_3 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_3, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_4 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_4, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_5 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_5, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_6 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_6, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_7 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_7, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_8 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_8, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_9 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_9, V_STAR_GRADE, P_USERLOGIN); END IF;
   IF P_HERO_ID_10 IS NOT NULL THEN SP_CRT_BD_HERO_TMP(V_BUILD_ID, P_HERO_ID_10, V_STAR_GRADE, P_USERLOGIN); END IF;
   
   --FIND SYNERGU AMONG THOSE HEROES
   SP_CRT_BD_SYNERGY_TMP(V_BUILD_ID, P_USERLOGIN);
   
   --SAVE NEW BUILD
   SP_SAVE_BUILD_LIST(V_BUILD_ID, P_USERLOGIN);
   
   COMMIT;

END;
/


