CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_ITEM_STAT_DETAIL (
   P_ITEM_STAT_DETAIL_ID    NUMBER,
   P_USERLOGIN              VARCHAR2,
   P_REASON                 VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_ITEM_STAT_DETAIL_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_ITEM_STAT_DETAIL A
       WHERE   A.ITEM_STAT_DETAIL_ID = P_ITEM_STAT_DETAIL_ID;

   DELETE FROM   CR_ITEM_STAT_DETAIL
         WHERE   ITEM_STAT_DETAIL_ID = P_ITEM_STAT_DETAIL_ID;

   COMMIT;
END;
/


