CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_SYNERGY_TYPE (
   P_SYNERGY_TYPE_ID    NUMBER,
   P_USERLOGIN          VARCHAR2,
   P_REASON             VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_SYNERGY_TYPE_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_SYNERGY_TYPE A
       WHERE   A.SYNERGY_TYPE_ID = P_SYNERGY_TYPE_ID;

   DELETE FROM   CR_SYNERGY_TYPE
         WHERE   SYNERGY_TYPE_ID = P_SYNERGY_TYPE_ID;

   COMMIT;
END;
/


