CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_BUILD_TMP (P_USERLOGIN VARCHAR2)
IS
BEGIN
   --DELETE TEMPORARY BUILD BY USER
   DELETE FROM   CR_BUILD_LIST_TMP
         WHERE   USER_CREATE = P_USERLOGIN;

   DELETE FROM   CR_BUILD_DETAIL_HERO_TMP
         WHERE   USER_CREATE = P_USERLOGIN;

   DELETE FROM   CR_BUILD_DETAIL_SYNERGY_TMP
         WHERE   USER_CREATE = P_USERLOGIN;

   COMMIT;
END;
/


