CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_SYNERGY_CODE (P_SYNERGY_CODE    VARCHAR2,
                                                 P_USERLOGIN       VARCHAR2,
                                                 P_REASON          VARCHAR2)
IS
BEGIN
   INSERT INTO CR_SYNERGY_CODE_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_SYNERGY_CODE A
       WHERE   A.SYNERGY_CODE = P_SYNERGY_CODE;

   DELETE FROM   CR_SYNERGY_CODE
         WHERE   SYNERGY_CODE = P_SYNERGY_CODE;

   COMMIT;
END;
/


