CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_PREVIEW_ARENA_BENCH (
   P_SESSION_ID    NUMBER
)
IS
BEGIN
   DELETE FROM   CR_PREVIEW_ARENA
         WHERE   SESSION_ID = P_SESSION_ID;

   DELETE FROM   CR_PREVIEW_BENCH
         WHERE   SESSION_ID = P_SESSION_ID;

   COMMIT;
END;
/


