CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_HERO_STAT_TYPE (
   P_STAT_TYPE_ID    NUMBER,
   P_USERLOGIN       VARCHAR2,
   P_REASON          VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_HERO_STAT_TYPE_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_HERO_STAT_TYPE A
       WHERE   A.STAT_TYPE_ID = P_STAT_TYPE_ID;

   DELETE FROM   CR_HERO_STAT_TYPE
         WHERE   STAT_TYPE_ID = P_STAT_TYPE_ID;

   COMMIT;
END;
/


