CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_HERO_STATUS (
   P_HERO_STATUS_CODE    VARCHAR2,
   P_USERLOGIN           VARCHAR2,
   P_REASON              VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_HERO_STATUS_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_HERO_STATUS A
       WHERE   A.HERO_STATUS_CODE = P_HERO_STATUS_CODE;

   DELETE FROM   CR_HERO_STATUS
         WHERE   HERO_STATUS_CODE = P_HERO_STATUS_CODE;

   COMMIT;
END;
/


