CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_DEL_BUILD_LIST (
   P_BUILD_ID     NUMBER,
   P_USERLOGIN    VARCHAR2,
   P_REASON       VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_SAVE_BUILD_LIST_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_SAVE_BUILD_LIST A
       WHERE   A.BUILD_ID = P_BUILD_ID;

   DELETE FROM   CR_SAVE_BUILD_LIST
         WHERE   BUILD_ID = P_BUILD_ID;

   COMMIT;
END;
/


