CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_SAVE_PREVIEW_BUILD (P_SESSION_ID    NUMBER,
                                                   P_BUILD_NAME    VARCHAR2,
                                                   P_USERLOGIN     VARCHAR2)
IS
   V_SESSION_ID   NUMBER;
   V_HERO_ID      NUMBER;
   V_STAR_GRADE   NUMBER;
   V_BUILD_NAME   VARCHAR2 (50 BYTE);
   V_BUILD_ID     NUMBER;
BEGIN
   --DEFINE BUILD NAME
   V_BUILD_NAME := P_BUILD_NAME;

   --CREATE BUILD TEMPORARY
   SP_CRT_BUILD_TMP (V_BUILD_NAME, P_USERLOGIN);

   --TAKE THE LAST BUILD_ID
   SELECT   BUILD_ID
     INTO   V_BUILD_ID
     FROM   CR_BUILD_LIST_TMP
    WHERE   USER_CREATE = P_USERLOGIN;

   --TAKE OUT 10 HEROES RANDOMLY FROM BENCH AND ARENA THAT HAVE HIGHEST STAR GRADE FOR EACH HERO
   --INSERT INTO LIST HERO TEMPORARY
   FOR I IN (  SELECT   SESSION_ID, HERO_ID, STAR_GRADE
                 INTO   V_SESSION_ID, V_HERO_ID, V_STAR_GRADE
                 FROM   V_PREVIEW_HERO
                WHERE   ROWNUM <= 10 AND SESSION_ID = P_SESSION_ID
             ORDER BY   DBMS_RANDOM.VALUE)
   LOOP
      SP_CRT_BD_HERO_TMP (V_BUILD_ID,
                          I.HERO_ID,
                          I.STAR_GRADE,
                          P_USERLOGIN);
   END LOOP;

   --DEFINE SYNERGY ID FROM LIST HERO TEMPORRARY
   SP_CRT_BD_SYNERGY_TMP (V_BUILD_ID, P_USERLOGIN);

   --SAVE NEW BUILD
   SP_SAVE_BUILD_LIST (V_BUILD_ID, P_USERLOGIN);

   --DELETE PREVIEW HERO ARENA AND BENCH
   SP_DEL_PREVIEW_ARENA_BENCH (P_SESSION_ID);

   COMMIT;
END;
/


