CREATE OR REPLACE PROCEDURE USER_CHESSRUSH.SP_UPD_HERO (
   P_HERO_ID             NUMBER,
   P_NEW_HERO_TIER_ID    NUMBER,
   P_NEW_HERO_NAME       VARCHAR2,
   P_USERLOGIN           VARCHAR2,
   P_REASON              VARCHAR2
)
IS
BEGIN
   INSERT INTO CR_HERO_DEL
      SELECT   A.*,
               SYSDATE AS DATE_DELETE,
               P_USERLOGIN AS USER_DELETE,
               P_REASON AS REASON_DELETE
        FROM   CR_HERO A
       WHERE   A.HERO_ID = P_HERO_ID;

   UPDATE   CR_HERO
      SET   HERO_TIER_ID = P_NEW_HERO_TIER_ID, HERO_NAME = P_NEW_HERO_NAME
    WHERE   HERO_ID = P_HERO_ID;

   COMMIT;
END;
/


