@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_API_ACCESS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_API_CLIENT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_API_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_MENU_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_MESSAGE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_PROFILE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_ROLE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_ROLE_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_ROLE_MENU_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER_INVALID_UNLOCK.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER_LOG.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\APP_USER_SESSION.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_BUILD_DETAIL_HERO_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_BUILD_DETAIL_SYNERGY_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_BUILD_LIST_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_CLASS_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_PHOTO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_PHOTO_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_RACE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_SKILL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_SKILL_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_SKILL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_SKILL_TYPE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STAT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STATUS_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STAT_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STAT_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_STAT_TYPE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_TAGLINE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_TAGLINE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_TIER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_HERO_TIER_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_ITEM.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_ITEM_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_ITEM_STAT_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_ITEM_STAT_DETAIL_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL_RARITY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL_RARITY_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_LEVEL_TYPE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_PREVIEW_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_PREVIEW_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SAVE_BUILD_LIST.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SAVE_BUILD_LIST_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_CODE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_CODE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_EFFECT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_EFFECT_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Tables\CR_SYNERGY_TYPE_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ACCESS_DETAIL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ACCESS_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ACCESS_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ACTIVATION_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_API_STATUS_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_BD_HERO_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_BD_SYNERGY_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_BUILD_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_CLASS_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_CLIENT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_PHOTO_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_SKILL_DETAIL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_SKILL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_STAT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_TAGLINE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HERO_TIER_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_HIT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_INVALID_UNLOCK_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ITEM_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ITEM_STAT_DETAIL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_KILL_SESSION_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_LEVEL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_LEVEL_RARITY_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_LEVEL_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_MENU_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_MESSAGE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_RACE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ROLE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_ROLE_MENU_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SAVE_BUILD_LIST_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SESSION_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SKILL_BASED_ON_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SKILL_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_STAT_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SYNERGY_EFFECT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SYNERGY_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_SYNERGY_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_UNIQUE_HIT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_USERLOG_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Sequences\SQ_USER_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_API_ACCESS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_API_CLIENT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_API_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_MESSAGE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_ROLE_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_USER_INVALID_UNLOCK.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_USER_LOG.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_APP_USER_SESSION.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_BD_HERO_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_BD_SYNERGY_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_BUILD_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_CLASS_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_CR_LEVEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_CR_LEVEL_RARITY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_CR_LEVEL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_CR_SYNERGY_EFFECT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_HERO_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_HERO_SKILL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_HERO_STAT_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_HERO_TAGLINE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_HERO_TIER_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_ITEM_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_ITEM_STAT_DETAIL_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_SAVE_BUILD_LIST_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_SKILL_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_STAT_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_SYNERGY_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Triggers\TRG_SYNERGY_TYPE_ID.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_APP_LAST_TOKEN.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_LVL_CHECK_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_LVL_CHECK_HERO_SLOT_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_LVL_CHECK_SLOT_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_PREVIEW_COMBINE_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_PREVIEW_SYNERGY_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Functions\F_PREVIEW_SYNERGY_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_INVALID_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_CHILD.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_ROLE_ALL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_ROLE_SELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_SELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_MENU_USELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_APP_ROLE_UNSELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_LVL_HERO_POOL_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_LVL_HERO_POOL_TIER_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_LVL_HERO_SLOT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_LVL_HERO_TIER_CHANCE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_LVL_HERO_TIER_SLOT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_MST_BUILD_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_MST_BUILD_SYNERGY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_MST_HERO_PROFILE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_COMBINE_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_COMBINE_HERO_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_COMBINE_HERO_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_COMBINE_UPGRADE_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_COMBINE_UPGRADE_SLOT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_SYNERGY_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_PREVIEW_SYNERGY_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_TMP_BUILD_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_TMP_BUILD_CLASS_SPECIAL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Views\V_TMP_BUILD_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_MENU_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_MENU_UNSELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_ROLE_UNSELECTED.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_DEL_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_MENU_ROLE_ALL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_STAT_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_STAT_UNIQUE_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_INS_USER_ACTIVATION.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_UNLOCK_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_UPD_MENU_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_UPD_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_APP_UPD_USER_ACTIVATION.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CHANGE_SLOT_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CHANGE_SLOT_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CHANGE_SLOT_BENCH_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_BD_HERO_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_BD_SYNERGY_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_BUILD_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_SIMPLE_BUILD_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_SLOT_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_CRT_SLOT_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_BUILD_LIST.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_BUILD_TMP.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_PHOTO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_SKILL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_SKILL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_STAT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_STAT_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_TAGLINE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_HERO_TIER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_ITEM.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_ITEM_STAT_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_PREVIEW_ARENA_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_SYNERGY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_SYNERGY_CODE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_DEL_SYNERGY_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_RESAVE_BUILD_LIST.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_SAVE_BUILD_LIST.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_SAVE_PREVIEW_BUILD.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPD_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPD_HERO_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPD_SLOT_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPD_SLOT_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPD_SYNERGY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPGRADE_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\Procedures\SP_UPGRADE_HERO_SPECIAL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_API_ACCESS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_API_CLIENT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_API_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_MESSAGE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_PROFILE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_ROLE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_ROLE_MENU.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_USER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_CLASS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_CLASS_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_PHOTO.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_RACE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_SKILL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_SKILL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_STAT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_STATUS.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_STAT_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_TAGLINE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_HERO_TIER.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_ITEM.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_ITEM_STAT_DETAIL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_LEVEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_LEVEL_RARITY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_LEVEL_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_PREVIEW_ARENA.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_PREVIEW_BENCH.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SAVE_BUILD_LIST.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SAVE_BUILD_LIST_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SYNERGY.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SYNERGY_CODE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SYNERGY_DEL.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SYNERGY_EFFECT.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\DML\CR_SYNERGY_TYPE.sql 
@C:\implementasi\deployment\USER_CHESSRUSH\Script\Deployment\RECOMPILE.sql  
